"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca,ea,da,ha,ia,ja,ka;
for(_.g,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this,ca=function(){ca=function(){};ba.Symbol||(ba.Symbol=da)},ea=0,da=function(a){return"jscomp_symbol_"+(a||"")+ea++},_.ga=function(){ca();var a=ba.Symbol.iterator;
a||(a=ba.Symbol.iterator=ba.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return _.fa(this)}});_.ga=function(){}},_.fa=function(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},ha=function(a){_.ga();a={next:a};a[ba.Symbol.iterator]=function(){return this};return a},ia=ba,ja=["String","prototype","repeat"],ka=0;ka<ja.length-1;ka++){var la=ja[ka];la in ia||(ia[la]={});ia=ia[la]}
var ma=ja[ja.length-1],na=ia[ma],oa=na?na:function(a){var b;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");b=this+"";if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};oa!=na&&null!=oa&&aa(ia,ma,{configurable:!0,writable:!0,value:oa});_.pa=_.pa||{};_.k=this;_.ra="closure_uid_"+(1E9*Math.random()>>>0);_.sa=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var ta,ua;_.m=function(a){return void 0!==a};ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ua=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.va=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Wc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.wa=function(a,b){a=a.split(".");var c=_.k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.m(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};_.xa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ua:ta;return _.q.apply(null,arguments)};
_.ya=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.za=function(a){return"function"==_.va(a)};_.Aa=function(a){return"number"==typeof a};_.r=function(a){return"string"==typeof a};_.Ba=function(a){var b=_.va(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Ca=function(a){return"array"==_.va(a)};_.Da=function(){};_.Ea=function(a){a=a.split(".");for(var b=_.k,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};
_.Fa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Fa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.Fa,Error);_.Fa.prototype.name="CustomError";var Ga;var Ka,Ma,Na,Oa,Pa,Qa,Ra,La,Ta,Wa;_.Ha=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ia=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ja=function(a){return/^[\s\xa0]*$/.test(a)};Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.Sa=function(a){if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Pa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Qa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ra,"&#0;"));return a};Ma=/&/g;Na=/</g;Oa=/>/g;Pa=/"/g;Qa=/'/g;Ra=/\x00/g;La=/[\x00&<>"']/;Ta=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ua=function(a){return null==a?"":String(a)};_.Va=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.sa)()).toString(36)};
_.Xa=function(a,b){var c=0;a=Ka(String(a)).split(".");b=Ka(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=Wa(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||Wa(0==f[2].length,0==h[2].length)||Wa(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; Wa=function(a,b){return a<b?-1:a>b?1:0};
var Ya;Ya=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.r(a))return _.r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Za=function(a,b){for(var c=_.r(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.$a=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.r(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var n=h[l];b.call(c,n,l,a)&&(e[f++]=n)}return e};
_.ab=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.r(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};_.bb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.db=function(a,b){b=_.cb(a,b,void 0);return 0>b?null:_.r(a)?a.charAt(b):a[b]};
_.cb=function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.eb=function(a,b){return 0<=Ya(a,b)};_.gb=function(a,b){b=Ya(a,b);var c;(c=0<=b)&&_.fb(a,b);return c};_.fb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.hb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.ib=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var kb=_.k.navigator;if(kb){var lb=kb.userAgent;if(lb){_.jb=lb;break a}}_.jb=""}_.v=function(a){return-1!=_.jb.indexOf(a)};var nb,ob,pb,rb;_.mb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};nb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};ob=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};pb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.qb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};rb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.sb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<rb.length;f++)c=rb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var tb=function(){return(_.v("Chrome")||_.v("CriOS"))&&!_.v("Edge")};var ub;ub=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};_.vb=function(){return _.v("Macintosh")};_.wb=function(){return _.v("Windows")};var xb=function(a){xb[" "](a);return a};xb[" "]=_.Da;_.yb=function(a,b){try{return xb(a[b]),!0}catch(c){}return!1};_.zb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var Ab,Bb,Eb,Ib,Jb,Nb,Ob,Qb;Ab=_.v("Opera");_.w=_.v("Trident")||_.v("MSIE");Bb=_.v("Edge");_.Cb=_.v("Gecko")&&!(-1!=_.jb.toLowerCase().indexOf("webkit")&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.Db=-1!=_.jb.toLowerCase().indexOf("webkit")&&!_.v("Edge");Eb=_.k.navigator||null;_.Fb=Eb&&Eb.platform||"";_.Gb=_.vb();_.Hb=_.wb();Ib=function(){var a=_.k.document;return a?a.documentMode:void 0};
a:{var Kb="",Lb=function(){var a=_.jb;if(_.Cb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Bb)return/Edge\/([\d\.]+)/.exec(a);if(_.w)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Db)return/WebKit\/(\S+)/.exec(a);if(Ab)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Lb&&(Kb=Lb?Lb[1]:"");if(_.w){var Mb=Ib();if(null!=Mb&&Mb>(0,window.parseFloat)(Kb)){Jb=String(Mb);break a}}Jb=Kb}Nb=Jb;Ob={};_.Pb=function(a){return _.zb(Ob,a,function(){return 0<=_.Xa(Nb,a)})};var Rb=_.k.document; Qb=Rb&&_.w?Ib()||("CSS1Compat"==Rb.compatMode?(0,window.parseInt)(Nb,10):5):void 0;
var Sb=_.v("Firefox"),Tb=ub()||_.v("iPod"),Ub=_.v("iPad"),Vb=_.v("Android")&&!(tb()||_.v("Firefox")||_.v("Opera")||_.v("Silk")),Wb=tb(),Xb=_.v("Safari")&&!(tb()||_.v("Coast")||_.v("Opera")||_.v("Edge")||_.v("Silk")||_.v("Android"))&&!(ub()||_.v("iPad")||_.v("iPod"));
var Yb=null;var Zb,$b,bc,ac,ec,fc,dc;Zb=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};$b=function(a){a=String(a);if(Zb(a))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.cc=function(a,b){var c=[];ac(new bc(b),a,c);return c.join("")};
bc=function(a){this.a=a};
ac=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.Ca(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],ac(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),dc(d,c),c.push(":"),ac(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":dc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};ec={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};fc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; dc=function(a,b){b.push('"',a.replace(fc,function(a){var b=ec[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ec[a]=b);return b}),'"')};
var ic,kc,lc,oc;_.y=function(){};_.gc="function"==typeof window.Uint8Array;_.z=function(a,b,c,d,e){a.b=null;b||(b=c?[c]:[]);a.o=c?String(c):void 0;a.h=0===c?-1:0;a.g=b;a:{if(a.g.length&&(b=a.g.length-1,(c=a.g[b])&&"object"==typeof c&&!_.Ca(c)&&!(_.gc&&c instanceof window.Uint8Array))){a.C=b-a.h;a.c=c;break a}a.C=Number.MAX_VALUE}a.m={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.C?(c+=a.h,a.g[c]=a.g[c]||_.hc):a.c[c]=a.c[c]||_.hc;e&&e.length&&(0,_.u)(e,_.xa(ic,a))};_.hc=[];
_.A=function(a,b){if(b<a.C){b+=a.h;var c=a.g[b];return c===_.hc?a.g[b]=[]:c}c=a.c[b];return c===_.hc?a.c[b]=[]:c};_.jc=function(a,b,c){a=_.A(a,b);return null==a?c:a};_.B=function(a,b,c){b<a.C?a.g[b+a.h]=c:a.c[b]=c};ic=function(a,b){var c,d;(0,_.u)(b,function(b){var e=_.A(a,b);null!=e&&(c=b,d=e,_.B(a,b,void 0))});return c?(_.B(a,c,d),c):0};_.C=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.A(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};
_.E=function(a,b,c){a.b||(a.b={});var d=c?_.D(c):c;a.b[b]=c;_.B(a,b,d)};kc=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.Ca(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){kc(a);return a.g};lc=_.k.JSON&&_.k.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.y.prototype.j=_.gc?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Yb){Yb={};for(var a=0;65>a;a++)Yb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Yb,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,l=h?this[e+1]:0,n=e+2<this.length,t=n?this[e+2]:0,x=f>>2,f=(f&3)<<4|l>>4,l=(l&15)<<2|t>>6,t=t&63;n||(t=64,h||(l=64));b.push(a[x],a[f],a[l],a[t])}return b.join("")};try{var b=lc.call(null,_.D(this),
mc)}finally{window.Uint8Array.prototype.toJSON=a}return b}:lc?function(){return lc.call(null,_.D(this),mc)}:function(){return _.cc(_.D(this),mc)};var mc=function(a,b){if(_.Aa(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.y.prototype.toString=function(){kc(this);return this.g.toString()};oc=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.nc(a[d],b[d]))return!1;return!0};
_.nc=function(a,b){if(a==b)return!0;if(!_.ya(a)||!_.ya(b)||a.constructor!=b.constructor)return!1;if(_.gc&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],l=b[c];h&&h.constructor==Object&&(d=h,h=void 0);l&&l.constructor==Object&&(e=l,l=void 0);if(!_.nc(h,l))return!1}return d||e?(d=d||{},e=e||{},oc(d,e)):!0}if(a.constructor=== Object)return oc(a,b);throw Error("e");};
_.F=function(){this.I=this.I;this.C=this.C};_.F.prototype.I=!1;_.F.prototype.$=function(){this.I||(this.I=!0,this.w())};_.I=function(a,b){_.G(a,_.xa(_.H,b))};_.G=function(a,b,c){a.I?_.m(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.m(c)?(0,_.q)(b,c):b))};_.F.prototype.w=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.$&&a.$()};
var pc=!_.w||9<=Number(Qb);!_.Cb&&!_.w||_.w&&9<=Number(Qb)||_.Cb&&_.Pb("1.9.1");_.w&&_.Pb("9");_.qc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.sc=function(){this.a="";this.g=_.rc;this.b=null};_.sc.prototype.lb=!0;_.sc.prototype.Ka=function(){return this.b};_.sc.prototype.mb=!0;_.sc.prototype.kb=function(){return this.a};_.rc={};_.tc=function(a,b){var c=new _.sc;c.a=a;c.b=b;return c};_.tc("<!DOCTYPE html>",0);_.tc("",0);_.uc=_.tc("<br>",0);
var Ac,Dc,Cc;_.xc=function(a){return a?new _.vc(_.wc(a)):Ga||(Ga=new _.vc)};_.zc=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.yc(window.document,"*",a,b)[0];return d||null};
_.yc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.eb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Bc=function(a,b){_.mb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Ac.hasOwnProperty(d)?a.setAttribute(Ac[d],b):_.Ha(d,"aria-")||_.Ha(d,"data-")?a.setAttribute(d,b):a[d]=b})};Ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
Dc=function(a,b,c){function d(c){c&&b.appendChild(_.r(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.Ba(f)||_.ya(f)&&0<f.nodeType?d(f):(0,_.u)(Cc(f)?_.ib(f):f,d)}};_.Ec=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.wc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};Cc=function(a){if(a&&"number"==typeof a.length){if(_.ya(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.za(a))return"function"==typeof a.item}return!1};
_.vc=function(a){this.a=a||_.k.document||window.document};_.g=_.vc.prototype;_.g.ya=_.xc;_.g.B=function(a){return _.r(a)?this.a.getElementById(a):a};
_.g.ma=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!pc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.Sa(h.name),'"');if(h.type){f.push(' type="',_.Sa(h.type),'"');var l={};_.sb(l,h);delete l.type;h=l}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.r(h)?f.className=h:_.Ca(h)?f.className=h.join(" "):_.Bc(f,h));2<e.length&&Dc(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
_.Fc=function(a){return function(){return a}}(!1);var Gc="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},Hc=function(){};Hc.prototype.next=function(){throw Gc;};Hc.prototype.ha=function(){return this};
var Ic=function(a){if(a instanceof Hc)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.Ba(a)){var b=0,c=new Hc;c.next=function(){for(;;){if(b>=a.length)throw Gc;if(b in a)return a[b++];b++}};return c}throw Error("f");},Jc=function(a,b){if(_.Ba(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==Gc)throw c;}else{a=Ic(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==Gc)throw c;}}},Kc=function(a){if(_.Ba(a))return _.ib(a);a=Ic(a);var b=[];Jc(a,function(a){b.push(a)});return b};
_.J=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.J?(c=a.V(),d=a.S()):(c=pb(a),d=ob(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.J.prototype.S=function(){Lc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.V=function(){Lc(this);return this.a.concat()};_.Nc=function(a,b){return Mc(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.J.prototype.remove=function(a){return Mc(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&Lc(this),!0):!1};var Lc=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Mc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Mc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return Mc(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){Mc(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.V(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ha=function(a){Lc(this);var b=0,c=this.c,d=this,e=new Hc;e.next=function(){if(c!=d.c)throw Error("g");if(b>=d.a.length)throw Gc;var e=d.a[b++];return a?e:d.b[e]};return e};var Mc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Pc;_.Oc=function(a){if(a.S&&"function"==typeof a.S)return a.S();if(_.r(a))return a.split("");if(_.Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ob(a)};
Pc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.Ba(a)||_.r(a))(0,_.u)(a,b,void 0);else{var c;if(a.V&&"function"==typeof a.V)c=a.V();else if(a.S&&"function"==typeof a.S)c=void 0;else if(_.Ba(a)||_.r(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=pb(a);for(var d=_.Oc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var Qc=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};Qc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var Rc=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};var Vc;_.Sc=[];_.Tc=[];_.Uc=!1;Vc=function(a){_.Sc[_.Sc.length]=a;if(_.Uc)for(var b=0;b<_.Tc.length;b++)a((0,_.q)(_.Tc[b].b,_.Tc[b]))};var Wc,Yc,Zc,Xc;Wc=function(a){_.k.setTimeout(function(){throw a;},0)};_.$c=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));c=Xc(c);!_.za(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&!_.v("Edge")&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Yc||(Yc=Zc()),Yc(c)):_.k.setImmediate(c)};
Zc=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.v("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.v("Trident")&&!_.v("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.vb;c.vb=null;a()}};return function(a){d.next={vb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};Xc=function(a){return a};Vc(function(a){Xc=a});
var ad=function(){this.b=this.a=null},cd=new Qc(function(){return new bd},function(a){a.reset()},100);ad.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var bd=function(){this.next=this.b=this.a=null};bd.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};bd.prototype.reset=function(){this.next=this.b=this.a=null};
var dd,ed,fd,gd,id;_.hd=function(a,b){dd||ed();fd||(dd(),fd=!0);var c=gd,d=cd.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d};ed=function(){var a=_.k.Promise;if(-1!=String(a).indexOf("[native code]")){var b=a.resolve(void 0);dd=function(){b.then(id)}}else dd=function(){_.$c(id)}};fd=!1;gd=new ad;id=function(){for(var a;a=gd.remove();){try{a.a.call(a.b)}catch(b){Wc(b)}Rc(cd,a)}fd=!1};
var jd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},kd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var nd,od,pd,vd,zd,ld,Cd,yd,wd;_.md=function(a,b){this.a=0;this.C=void 0;this.c=this.b=this.g=null;this.h=this.j=!1;if(a!=_.Da)try{var c=this;a.call(b,function(a){ld(c,2,a)},function(a){ld(c,3,a)})}catch(d){ld(this,3,d)}};nd=function(){this.next=this.context=this.b=this.c=this.a=null;this.g=!1};nd.prototype.reset=function(){this.context=this.b=this.c=this.a=null;this.g=!1};od=new Qc(function(){return new nd},function(a){a.reset()},100);pd=function(a,b,c){var d=od.get();d.c=a;d.b=b;d.context=c;return d};
_.qd=function(a){if(a instanceof _.md)return a;var b=new _.md(_.Da);ld(b,2,a);return b};_.sd=function(){var a,b=new _.md(function(b){a=b});return new rd(b,a)};_.md.prototype.then=function(a,b,c){return _.td(this,_.za(a)?a:null,_.za(b)?b:null,c)};jd(_.md);_.md.prototype.cancel=function(a){0==this.a&&_.hd(function(){var b=new ud(a);vd(this,b)},this)};
vd=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?vd(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):wd(c),xd(c,e,3,b)))}a.g=null}else ld(a,3,b)};zd=function(a,b){a.b||2!=a.a&&3!=a.a||yd(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.td=function(a,b,c,d){var e=pd(null,null,null);e.a=new _.md(function(a,h){e.c=b?function(c){try{var e=b.call(d,c);a(e)}catch(t){h(t)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof ud?h(b):a(e)}catch(t){h(t)}}:h});e.a.g=a;zd(a,e);return e.a};_.md.prototype.m=function(a){this.a=0;ld(this,2,a)};_.md.prototype.o=function(a){this.a=0;ld(this,3,a)};
ld=function(a,b,c){0==a.a&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.a=1,_.Ad(c,a.m,a.o,a)||(a.C=c,a.a=b,a.g=null,yd(a),3!=b||c instanceof ud||Bd(a,c)))};_.Ad=function(a,b,c,d){if(a instanceof _.md)return zd(a,pd(b||_.Da,c||null,d)),!0;if(kd(a))return a.then(b,c,d),!0;if(_.ya(a))try{var e=a.then;if(_.za(e))return Cd(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
Cd=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(n){l(n)}};yd=function(a){a.j||(a.j=!0,_.hd(a.l,a))};wd=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.md.prototype.l=function(){for(var a;a=wd(this);)xd(this,a,this.a,this.C);this.j=!1};
var xd=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,Dd(b,c,d);else try{b.g?b.c.call(b.context):Dd(b,c,d)}catch(e){Ed.call(null,e)}Rc(od,b)},Dd=function(a,b,c){2==b?a.c.call(a.context,c):a.b&&a.b.call(a.context,c)},Bd=function(a,b){a.h=!0;_.hd(function(){a.h&&Ed.call(null,b)})},Ed=Wc,ud=function(a){_.Fa.call(this,a)};_.p(ud,_.Fa);ud.prototype.name="cancel";var rd=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Fd=function(a,b){this.l=[];this.G=a;this.v=b||null;this.j=this.g=!1;this.c=void 0;this.J=this.K=this.o=!1;this.m=0;this.a=null;this.C=0};_.Fd.prototype.cancel=function(a){if(this.g)this.c instanceof _.Fd&&this.c.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.G?this.G.call(this.v,this):this.J=!0;this.g||this.D(new _.Gd)}};_.Fd.prototype.H=function(a,b){this.o=!1;Hd(this,a,b)};
var Hd=function(a,b,c){a.g=!0;a.c=c;a.j=!b;Id(a)},Kd=function(a){if(a.g){if(!a.J)throw new Jd;a.J=!1}};_.Fd.prototype.b=function(a){Kd(this);Hd(this,!0,a)};_.Fd.prototype.D=function(a){Kd(this);Hd(this,!1,a)};_.Md=function(a,b,c){_.Ld(a,b,null,c)};_.Ld=function(a,b,c,d){a.l.push([b,c,d]);a.g&&Id(a)};_.Fd.prototype.then=function(a,b,c){var d,e,f=new _.md(function(a,b){d=a;e=b});_.Ld(this,d,function(a){a instanceof _.Gd?f.cancel():e(a)});return f.then(a,b,c)};jd(_.Fd);
_.Nd=function(a,b){b instanceof _.Fd?_.Md(a,(0,_.q)(b.h,b)):_.Md(a,function(){return b})};_.Fd.prototype.h=function(a){var b=new _.Fd;_.Ld(this,b.b,b.D,b);a&&(b.a=this,this.C++);return b};
var Od=function(a){return(0,_.bb)(a.l,function(a){return _.za(a[1])})},Id=function(a){if(a.m&&a.g&&Od(a)){var b=a.m,c=Pd[b];c&&(_.k.clearTimeout(c.a),delete Pd[b]);a.m=0}a.a&&(a.a.C--,delete a.a);for(var b=a.c,d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var l=f.call(e||a.v,b);_.m(l)&&(a.j=a.j&&(l==b||l instanceof Error),a.c=b=l);if(kd(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.o=!0}catch(n){b=n,a.j=!0,Od(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.H,
a,!0),d=(0,_.q)(a.H,a,!1),b instanceof _.Fd?(_.Ld(b,l,d),b.K=!0):b.then(l,d));c&&(b=new Qd(b),Pd[b.a]=b,a.m=b.a)},Jd=function(){_.Fa.call(this)};_.p(Jd,_.Fa);Jd.prototype.message="Deferred has already fired";Jd.prototype.name="AlreadyCalledError";_.Gd=function(){_.Fa.call(this)};_.p(_.Gd,_.Fa);_.Gd.prototype.message="Deferred was canceled";_.Gd.prototype.name="CanceledError";var Qd=function(a){this.a=_.k.setTimeout((0,_.q)(this.g,this),0);this.b=a}; Qd.prototype.g=function(){delete Pd[this.a];throw this.b;};var Pd={};
var Rd=!_.w||9<=Number(Qb),Sd=_.w&&!_.Pb("9");!_.Db||_.Pb("528");_.Cb&&_.Pb("1.9b")||_.w&&_.Pb("8")||Ab&&_.Pb("9.5")||_.Db&&_.Pb("528");_.Cb&&!_.Pb("8")||_.w&&_.Pb("9");_.K=function(a,b){this.type="undefined"!=typeof _.Td&&a instanceof _.Td?String(a):a;this.b=this.target=b;this.c=!1;this.Ab=!0};_.K.prototype.l=function(){this.c=!0};_.K.prototype.g=function(){this.Ab=!1};var Ud=function(a,b){_.K.call(this,a?a.type:"");this.b=this.target=null;this.keyCode=0;this.C=this.m=this.h=this.j=!1;this.a=this.state=null;a&&(this.type=a.type,this.target=a.target||a.srcElement,this.b=b,(b=a.relatedTarget)&&_.Cb&&_.yb(b,"nodeName"),this.keyCode=a.keyCode||0,this.j=a.ctrlKey,this.h=a.altKey,this.m=a.shiftKey,this.C=a.metaKey,this.state=a.state,this.a=a,a.defaultPrevented&&this.g())};_.p(Ud,_.K);
Ud.prototype.l=function(){Ud.A.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Ud.prototype.g=function(){Ud.A.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Sd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Vd="closure_listenable_"+(1E6*Math.random()|0),Wd=function(a){return!(!a||!a[Vd])},Xd=0;var Yd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ma=e;this.key=++Xd;this.removed=this.Ia=!1},Zd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ma=null};var $d=function(a){this.src=a;this.a={};this.b=0},be=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var l=ae(b,c,e,f);-1<l?(a=b[l],d||(a.Ia=!1)):(a=new Yd(c,a.src,h,!!e,f),a.Ia=d,b.push(a));return a};$d.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=ae(e,b,c,d);return-1<b?(Zd(e[b]),_.fb(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ce=function(a,b){var c=b.type;c in a.a&&_.gb(a.a[c],b)&&(Zd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};$d.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Zd(d[e]);delete this.a[c];this.b--}return b};
var de=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=ae(a,c,d,e));return-1<b?a[b]:null},ee=function(a){var b=_.m(void 0)?"undefined":void 0,c=_.m(b),d=c?b.toString():"",e=_.m(void 0);return nb(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})},ae=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ma==d)return e}return-1};
var fe,ge,he,ke,me,re,ne,te,se,oe,le,ue,je;fe="closure_lm_"+(1E6*Math.random()|0);ge={};he=0;_.ie=function(a,b,c,d,e){if(_.Ca(b)){for(var f=0;f<b.length;f++)_.ie(a,b[f],c,d,e);return null}c=je(c);return Wd(a)?a.listen(b,c,d,e):ke(a,b,c,!1,d,e)};
ke=function(a,b,c,d,e,f){if(!b)throw Error("h");var h=!!e,l=le(a);l||(a[fe]=l=new $d(a));c=be(l,b,c,d,e,f);if(c.proxy)return c;d=me();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(ne(b.toString()),d);else throw Error("i");he++;return c};me=function(){var a=oe,b=Rd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.pe=function(a,b,c,d,e){if(_.Ca(b)){for(var f=0;f<b.length;f++)_.pe(a,b[f],c,d,e);return null}c=je(c);return Wd(a)?a.La(b,c,d,e):ke(a,b,c,!0,d,e)};_.qe=function(a,b,c,d,e){if(_.Ca(b))for(var f=0;f<b.length;f++)_.qe(a,b[f],c,d,e);else c=je(c),Wd(a)?a.Pa(b,c,d,e):a&&(a=le(a))&&(b=de(a,b,c,!!d,e))&&re(b)};
re=function(a){if(!_.Aa(a)&&a&&!a.removed){var b=a.src;if(Wd(b))ce(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(ne(c),d);he--;(c=le(b))?(ce(c,a),0==c.b&&(c.src=null,b[fe]=null)):Zd(a)}}};ne=function(a){return a in ge?ge[a]:ge[a]="on"+a};te=function(a,b,c,d){var e=!0;if(a=le(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=se(f,d),e=e&&!1!==f)}return e};
se=function(a,b){var c=a.listener,d=a.Ma||a.src;a.Ia&&re(a);return c.call(d,b)};
oe=function(a,b){if(a.removed)return!0;if(!Rd){var c=b||_.Ea("window.event");b=new Ud(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=te(c[e],a,!0,b),d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=te(c[e],a,!1,b),d=d&&f}return d}return se(a,new Ud(b,this))}; le=function(a){a=a[fe];return a instanceof $d?a:null};ue="__closure_events_fn_"+(1E9*Math.random()>>>0);je=function(a){if(_.za(a))return a;a[ue]||(a[ue]=function(b){return a.handleEvent(b)});return a[ue]};Vc(function(a){oe=a(oe)});
_.L=function(){_.F.call(this);this.g=new $d(this);this.fa=this;this.J=null};_.p(_.L,_.F);_.L.prototype[Vd]=!0;_.L.prototype.H=function(a){this.J=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.qe(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.J;if(d)for(c=[];d;d=d.J)c.push(d);a=a.fa;d=b.type||b;if(_.r(b))b=new _.K(b,a);else if(b instanceof _.K)b.target=b.target||a;else{var e=b;b=new _.K(d,a);_.sb(b,e)}var e=!0,f;if(c)for(var h=c.length-1;!b.c&&0<=h;h--)f=b.b=c[h],e=f.oa(d,!0,b)&&e;b.c||(f=b.b=a,e=f.oa(d,!0,b)&&e,b.c||(e=f.oa(d,!1,b)&&e));if(c)for(h=0;!b.c&&h<c.length;h++)f=b.b=c[h],e=f.oa(d,!1,b)&&e;return e};_.g=_.L.prototype;_.g.w=function(){_.L.A.w.call(this);this.g&&this.g.removeAll(void 0);this.J=null};
_.g.listen=function(a,b,c,d){return be(this.g,String(a),b,!1,c,d)};_.g.La=function(a,b,c,d){return be(this.g,String(a),b,!0,c,d)};_.g.Pa=function(a,b,c,d){return this.g.remove(String(a),b,c,d)};_.g.oa=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,l=f.Ma||f.src;f.Ia&&ce(this.g,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.Ab};
var ve=function(){};ve.prototype.a=null;var xe=function(a){var b;(b=a.a)||(b={},we(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var ye,ze=function(){};_.p(ze,ve);var Ae=function(a){return(a=we(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},we=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("j");}return a.b};ye=new ze;
_.Be=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.k;this.c=(0,_.q)(this.Ec,this);this.h=(0,_.sa)()};_.p(_.Be,_.L);_.g=_.Be.prototype;_.g.ra=!1;_.g.W=null;_.g.setInterval=function(a){this.b=a;this.W&&this.ra?(this.stop(),this.start()):this.W&&this.stop()};
_.g.Ec=function(){if(this.ra){var a=(0,_.sa)()-this.h;0<a&&a<.8*this.b?this.W=this.a.setTimeout(this.c,this.b-a):(this.W&&(this.a.clearTimeout(this.W),this.W=null),_.M(this,"tick"),this.ra&&(this.W=this.a.setTimeout(this.c,this.b),this.h=(0,_.sa)()))}};_.g.start=function(){this.ra=!0;this.W||(this.W=this.a.setTimeout(this.c,this.b),this.h=(0,_.sa)())};_.g.stop=function(){this.ra=!1;this.W&&(this.a.clearTimeout(this.W),this.W=null)};_.g.w=function(){_.Be.A.w.call(this);this.stop();delete this.a}; _.Ce=function(a,b,c){if(_.za(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("k");return 2147483647<Number(b)?-1:_.k.setTimeout(a,b||0)};_.De=function(a){_.k.clearTimeout(a)};
var Ee=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Fe=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,f=null;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?(0,window.decodeURIComponent)(f.replace(/\+/g," ")):"")}}};
var Ge=function(a){_.L.call(this);this.headers=new _.J;this.D=a||null;this.b=!1;this.v=this.a=null;this.M="";this.j=0;this.h="";this.c=this.K=this.m=this.G=!1;this.l=0;this.o=null;this.Z="";this.T=this.U=!1},He,Ie,Re,Qe,Ne,Se,Te;_.p(Ge,_.L);He=/^https?$/i;Ie=["POST","PUT"];_.Je=[];_.Ke=function(a,b,c,d,e,f,h){var l=new Ge;_.Je.push(l);b&&l.listen("complete",b);l.La("ready",l.ga);f&&(l.l=Math.max(0,f));h&&(l.U=h);l.send(a,c,d,e)};Ge.prototype.ga=function(){this.$();_.gb(_.Je,this)};
Ge.prototype.send=function(a,b,c,d){if(this.a)throw Error("l`"+this.M+"`"+a);b=b?b.toUpperCase():"GET";this.M=a;this.h="";this.j=0;this.G=!1;this.b=!0;this.a=this.D?Ae(this.D):Ae(ye);this.v=this.D?xe(this.D):xe(ye);this.a.onreadystatechange=(0,_.q)(this.Y,this);try{this.K=!0,this.a.open(b,String(a),!0),this.K=!1}catch(f){Le(this,f);return}a=c||"";var e=new _.J(this.headers);d&&Pc(d,function(a,b){e.set(b,a)});d=_.db(e.V(),Me);c=_.k.FormData&&a instanceof _.k.FormData;!_.eb(Ie,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Z&&(this.a.responseType=this.Z);"withCredentials"in this.a&&this.a.withCredentials!==this.U&&(this.a.withCredentials=this.U);try{Ne(this),0<this.l&&((this.T=Oe(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.q)(this.X,this)):this.o=_.Ce(this.X,this.l,this)),this.m=!0,this.a.send(a),this.m=!1}catch(f){Le(this,f)}};
var Oe=function(a){return _.w&&_.Pb(9)&&_.Aa(a.timeout)&&_.m(a.ontimeout)},Me=function(a){return"content-type"==a.toLowerCase()};Ge.prototype.X=function(){"undefined"!=typeof _.pa&&this.a&&(this.h="Timed out after "+this.l+"ms, aborting",this.j=8,_.M(this,"timeout"),this.abort(8))};var Le=function(a,b){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.h=b;a.j=5;Pe(a);Qe(a)},Pe=function(a){a.G||(a.G=!0,_.M(a,"complete"),_.M(a,"error"))};
Ge.prototype.abort=function(a){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,this.j=a||7,_.M(this,"complete"),_.M(this,"abort"),Qe(this))};Ge.prototype.w=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Qe(this,!0));Ge.A.w.call(this)};Ge.prototype.Y=function(){this.I||(this.K||this.m||this.c?Re(this):this.N())};Ge.prototype.N=function(){Re(this)};
Re=function(a){if(a.b&&"undefined"!=typeof _.pa&&(!a.v[1]||4!=Se(a)||2!=Te(a)))if(a.m&&4==Se(a))_.Ce(a.Y,0,a);else if(_.M(a,"readystatechange"),4==Se(a)){a.b=!1;try{if(_.Ue(a))_.M(a,"complete"),_.M(a,"success");else{a.j=6;var b;try{b=2<Se(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+Te(a)+"]";Pe(a)}}finally{Qe(a)}}};Qe=function(a,b){if(a.a){Ne(a);var c=a.a,d=a.v[0]?_.Da:null;a.a=null;a.v=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
Ne=function(a){a.a&&a.T&&(a.a.ontimeout=null);_.Aa(a.o)&&(_.De(a.o),a.o=null)};_.Ue=function(a){var b=Te(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.M).match(Ee)[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!He.test(a?a.toLowerCase():"");c=b}return c};Se=function(a){return a.a?a.a.readyState:0};Te=function(a){try{return 2<Se(a)?a.a.status:-1}catch(b){return-1}}; _.Ve=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};Vc(function(a){Ge.prototype.N=a(Ge.prototype.N)});
var Xe;_.N=function(a){_.F.call(this);this.T=a;this.J={}};_.p(_.N,_.F);var We=[];_.N.prototype.listen=function(a,b,c,d){_.Ca(b)||(b&&(We[0]=b.toString()),b=We);for(var e=0;e<b.length;e++){var f=_.ie(a,b[e],c||this.handleEvent,d||!1,this.T||this);if(!f)break;this.J[f.key]=f}return this};_.Ye=function(a,b,c,d){Xe(a,b,c,d,void 0)};Xe=function(a,b,c,d,e,f){if(_.Ca(c))for(var h=0;h<c.length;h++)Xe(a,b,c[h],d,e,f);else(b=_.pe(b,c,d||a.handleEvent,e,f||a.T||a))&&(a.J[b.key]=b)};
_.N.prototype.Pa=function(a,b,c,d,e){if(_.Ca(b))for(var f=0;f<b.length;f++)this.Pa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.T||this,c=je(c),d=!!d,b=Wd(a)?de(a.g,String(b),c,d,e):a?(a=le(a))?de(a,b,c,d,e):null:null,b&&(re(b),delete this.J[b.key]);return this};_.N.prototype.removeAll=function(){_.mb(this.J,function(a,b){this.J.hasOwnProperty(b)&&re(a)},this);this.J={}};_.N.prototype.w=function(){_.N.A.w.call(this);this.removeAll()};_.N.prototype.handleEvent=function(){throw Error("m");};
var af=function(){};af.prototype.c=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var bf=function(a){(a?a:function(){}).Yb=!0};_.cf=function(){};_.p(_.cf,af);_.cf.prototype.b=function(a){return a};bf(_.cf.prototype.b);_.cf.prototype.g=function(){return!0};bf(_.cf.prototype.g);var df=function(a){_.z(this,a,0,null,null)};_.p(df,_.y);var ef;ef=function(a,b){var c=new df;_.B(c,1,b);_.B(c,2,a);return c};_.ff=ef("?",0);_.gf=ef("q",1);_.hf=ef("<",2);_.jf=ef(">",3);_.kf=ef("~",4);_.lf=ef("s",5);_.O=function(a,b,c){this.g=a;this.b=b||null;this.a=c||[]};_.O.prototype.toString=function(){return this.g};var mf,nf,of,rf,tf,Cf,uf,wf,vf,zf,xf,sf,Df;_.P=function(a,b){this.b=this.C=this.h="";this.c=null;this.l=this.a="";this.j=!1;var c;a instanceof _.P?(this.j=_.m(b)?b:a.j,mf(this,a.h),this.C=a.C,this.b=a.b,nf(this,a.c),this.a=a.a,of(this,pf(a.g)),_.qf(this,a.l)):a&&(c=String(a).match(Ee))?(this.j=!!b,mf(this,c[1]||"",!0),this.C=rf(c[2]||""),this.b=rf(c[3]||"",!0),nf(this,c[4]),this.a=rf(c[5]||"",!0),of(this,c[6]||"",!0),_.qf(this,c[7]||"",!0)):(this.j=!!b,this.g=new sf(null,0,this.j))};
_.P.prototype.toString=function(){var a=[],b=this.h;b&&a.push(tf(b,uf,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.C)&&a.push(tf(b,uf,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(tf(c,"/"==c.charAt(0)?vf:wf,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",tf(c,xf));return a.join("")};
mf=function(a,b,c){a.h=c?rf(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};nf=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("r`"+b);a.c=b}else a.c=null};of=function(a,b,c){b instanceof sf?(a.g=b,yf(a.g,a.j)):(c||(b=tf(b,zf)),a.g=new sf(b,0,a.j))};_.Q=function(a,b,c){a.g.set(b,c)};_.qf=function(a,b,c){a.l=c?rf(b):b};_.Af=function(a){return a instanceof _.P?new _.P(a):new _.P(a,void 0)};
_.Bf=function(a,b){a instanceof _.P||(a=_.Af(a));b instanceof _.P||(b=_.Af(b));var c=a;a=new _.P(c);var d=!!b.h;d?mf(a,b.h):d=!!b.C;d?a.C=b.C:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)nf(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var c=_.Ha(e,"/"),e=e.split("/"),f=[],h=0;h<e.length;){var l=e[h++];"."==l?c&&h==e.length&&f.push(""):".."==l?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(l),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?of(a,pf(b.g)):d=!!b.l;d&&_.qf(a,b.l);return a};rf=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};tf=function(a,b,c){return _.r(a)?(a=(0,window.encodeURI)(a).replace(b,Cf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Cf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
uf=/[#\/\?@]/g;wf=/[\#\?:]/g;vf=/[\#\?]/g;zf=/[\#\?@]/g;xf=/#/g;sf=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};Df=function(a){a.a||(a.a=new _.J,a.b=0,a.g&&Fe(a.g,function(b,c){b=(0,window.decodeURIComponent)(b.replace(/\+/g," "));Df(a);a.g=null;b=Ef(a,b);var d=a.a.get(b);d||a.a.set(b,d=[]);d.push(c);a.b+=1}))};sf.prototype.remove=function(a){Df(this);a=Ef(this,a);return _.Nc(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
sf.prototype.clear=function(){this.a=this.g=null;this.b=0};var Ff=function(a,b){Df(a);b=Ef(a,b);return _.Nc(a.a,b)};sf.prototype.V=function(){Df(this);for(var a=this.a.S(),b=this.a.V(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};sf.prototype.S=function(a){Df(this);var b=[];if(_.r(a))Ff(this,a)&&(b=_.hb(b,this.a.get(Ef(this,a))));else{a=this.a.S();for(var c=0;c<a.length;c++)b=_.hb(b,a[c])}return b};
sf.prototype.set=function(a,b){Df(this);this.g=null;a=Ef(this,a);Ff(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};sf.prototype.get=function(a,b){a=a?this.S(a):[];return 0<a.length?String(a[0]):b};_.Gf=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Ef(a,b),_.ib(c)),a.b+=c.length)};
sf.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.V(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.S(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.g=a.join("&")};
var pf=function(a){var b=new sf;b.g=a.g;a.a&&(b.a=new _.J(a.a),b.b=a.b);return b},Ef=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},yf=function(a,b){b&&!a.c&&(Df(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Gf(this,c,a))},a));a.c=b};
_.cf.A||_.p(_.cf,af);_.Hf=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
_.If=function(a){_.z(this,a,"uv_r_rdm",null,null)};_.p(_.If,_.y);_.If.messageId="uv_r_rdm";_.Jf=function(a){_.z(this,a,"uv_r_rr",null,null)};_.p(_.Jf,_.y);_.Jf.messageId="uv_r_rr";_.Kf=function(a){_.z(this,a,"uv_r_frm",null,null)};_.p(_.Kf,_.y);_.Kf.messageId="uv_r_frm";_.Lf=function(a){_.z(this,a,0,null,null)};_.p(_.Lf,_.y);
var Nf=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("t");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,l,n,t,x,U){if("%"==t)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("u");arguments[0]=e;return Mf[t].apply(null,arguments)})},Mf={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Ta(" ",Number(c)-a.length):Ta(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ta(" ",a):f+Ta(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,l){return Mf.f((0,window.parseInt)(a,10),b, c,d,0,f,h,l)}};Mf.i=Mf.d;Mf.u=Mf.d;
_.R=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Nf("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+Nf(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Nf.apply({},c)))};
_.Of=new _.O("pVbxBc");_.S=new _.O("nED8Yb");_.Pf=new _.O("xclgJb");_.Qf=new _.O("Qz9Lj");_.Sf=function(a){_.z(this,a,"h_exts",Rf,null)};_.p(_.Sf,_.y);var Rf=[2];_.Sf.messageId="h_exts";_.Tf=function(a){return _.Bf(a,"/webchat/host-js")};_.Uf=function(a){var b=_.Tf(_.A(a,2));_.Q(b,"prop",_.Hf(27));_.Q(b,"b",1);_.Q(b,"hl",_.A(a,3));_.A(a,4)&&_.Q(b,"jsmode",_.A(a,4));_.Q(b,"zx",_.Va());return b.toString()};var Vf;Vf=function(a){return(a=a.exec(_.jb))?a[1]:""};_.Wf=function(){if(Sb)return Vf(/Firefox\/([0-9.]+)/);if(_.w||Bb||Ab)return Nb;if(Wb)return Vf(/Chrome\/([0-9.]+)/);if(Xb&&!(ub()||_.v("iPad")||_.v("iPod")))return Vf(/Version\/([0-9.]+)/);if(Tb||Ub){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.jb);if(a)return a[1]+"."+a[2]}else if(Vb)return(a=Vf(/Android\s+([0-9.]+)/))?a:Vf(/Version\/([0-9.]+)/);return""}();
var Xf=function(a,b){_.K.call(this,a,b);this.P=b};_.p(Xf,_.K);var Yf=function(a){_.z(this,a,"capi_md1571",null,null)};_.p(Yf,_.y);Yf.messageId="capi_md1571";var Zf={rb:0,Kc:1,Ic:2,qb:3,ab:4},$f=function(a){_.z(this,a,0,null,null)};_.p($f,_.y);var bg=function(){for(var a=10,b=ag,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},ag="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.cg=function(a,b){_.F.call(this);this.j=b||bg();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.N(this);_.I(this,this.h);this.h.listen(window,"message",this.m)};_.p(_.cg,_.F);_.cg.prototype.ca=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.cg.prototype.m=function(a){a=a.a;var b;b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.P(b)).b,b=_.Ia(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.r(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.Ca(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new Yf(c),_.A(c,1)==this.j)){b=_.A(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ca(a.origin,a.source);
1==_.A(c,2)?this.send(2):this.l(c,a)}}};_.cg.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new Yf;_.B(b,3,this.j);_.B(b,1,this.a);_.B(b,2,a);var d=JSON.stringify(_.D(b)),e=this.g,f=this.c;_.w?_.Ce(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var dg=function(a,b,c,d,e){this.g=_.sd();this.a=new _.cg((0,_.q)(this.h,this),d);this.a.ca(a,b,e);this.a.a=c;this.b=new _.Be(50);this.b.start();_.ie(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.j;b=pd(b,b,this);b.g=!0;zd(a,b)};dg.prototype.j=function(){_.H(this.a);_.qe(this.b,"tick",this.c,!1,this);_.H(this.b)};dg.prototype.c=function(){this.a.send(1)};dg.prototype.h=function(a,b){2==_.A(a,2)&&this.g.b(b.origin)};
var eg=function(a,b,c){_.F.call(this);this.b=a;a=_.A(b,3);b=_.A(b,1);this.a=new _.cg((0,_.q)(this.g,this),b);this.a.a=a;c&&this.a.ca(c.origin,c.source);_.I(this,this.a)};_.p(eg,_.F);eg.prototype.send=function(a){var b=new Yf;_.E(b,4,a);this.a.send(Zf.rb,b)};eg.prototype.connect=function(a,b){this.a.ca(a,b);this.a.send(Zf.qb)};eg.prototype.g=function(a){_.A(a,2)==Zf.rb&&(a=_.C(a,$f,4),this.b(a))};eg.prototype.c=_.Da;
var gg=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],fg(this)):(this.a=new _.cg(_.Da,_.A(b,1)),a=_.A(b,3),this.a.a=a)};_.p(gg,_.F);gg.prototype.w=function(){gg.A.w.call(this);this.b&&this.b.close();_.H(this.a)};gg.prototype.c=function(){this.g=new _.N(this);_.I(this,this.g);fg(this)};gg.prototype.send=function(a){this.b.postMessage(_.D(a))};
gg.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;fg(this);var d=this.a;this.a=null;c=c.port2;d.ca(a,b);d.send(Zf.ab,void 0,[c]);_.H(d)};var fg=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};gg.prototype.j=function(a){a=a.a;var b;try{b=new $f(a.data)}catch(c){return}this.h(b)};
var hg=function(a,b,c){var d=!1;_.m(_.A(b,2))?_.A(b,2)==Zf.ab&&(d=!0):d=Wb;return d?new gg(a,b,c):new eg(a,b,c)};var lg;_.ig=function(){_.L.call(this);this.h=null;this.l=!1;this.j=[];this.c=[];_.G(this,this.o,this);this.b=null};_.p(_.ig,_.L);_.ig.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.kg=function(a){a.o();a.j=[];a.b=new _.Fd;a.c.push((0,_.q)(a.b.cancel,a.b));a.l=!1;_.Md(a.b.h(),function(a){(ee(this.g)||this.J)&&jg(this);this.c.push(_.xa(_.H,a))},a)};_.g=_.ig.prototype;_.g.sendMessage=function(a){this.xa(_.D(a))};_.g.xa=function(a){if(this.b){var b=new $f;_.B(b,1,a);_.Md(this.b.h(),function(a){a.send(b)})}};
_.g.pb=function(a){this.h=a;_.G(this,function(){this.h=null},this);jg(this)};_.g.F=function(){return this};_.g.ca=function(a,b,c){this.a.ca(a,b,c)};_.mg=function(a,b,c,d){_.kg(a);lg(a,b,c,d).then(function(a){var d=new Yf;_.B(d,1,a.Fc);_.B(d,3,c);d=hg((0,_.q)(this.m,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};lg=function(a,b,c,d){var e=bg();b=(new dg("*",b,c,e,d)).g.a;a.c.push((0,_.q)(b.cancel,b));return b.then(function(a){return{Fc:e,origin:a}})};
_.ig.prototype.D=function(a,b){if(_.A(a,2)==Zf.qb||_.A(a,2)==Zf.ab)_.H(this.a),this.a=null,this.b.b(hg((0,_.q)(this.m,this),a,b))};_.ig.prototype.m=function(a){this.j.push(a);this.v()};_.ig.prototype.v=function(){for(;ng(this););};var ng=function(a){if(a.I||!a.l||0==a.j.length)return!1;var b=_.A(a.j.shift(),1);a.h&&a.h.xa(b);_.M(a,new Xf(b[0],b));return!0},jg=function(a){a.l||(a.l=!0,a.b&&_.Md(a.b.h(),function(a){a.c();_.Ce(this.v,0,this)},a))}; _.ig.prototype.listen=function(a,b,c,d){jg(this);return _.ig.A.listen.call(this,a,b,c,d)};_.ig.prototype.La=function(a,b,c,d){jg(this);return _.ig.A.La.call(this,a,b,c,d)};_.ig.prototype.H=function(a){jg(this);return _.ig.A.H.call(this,a)};
var og=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};og.prototype.setVersion=function(a){this.c=a;return this};og.prototype.Na=function(a){this.a=a;return this};og.prototype.ob=function(a){this.g=_.qb(a);return this};var pg=function(){};var qg=function(){};_.p(qg,pg);qg.prototype.clear=function(){var a=Kc(this.ha(!0)),b=this;(0,_.u)(a,function(a){b.remove(a)})};var rg=function(a){this.a=a};_.p(rg,qg);_.g=rg.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.r(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ha=function(a){var b=0,c=this.a,d=new Hc;d.next=function(){if(b>=c.length)throw Gc;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.r(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var sg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.p(sg,rg);var ug=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new sg);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=$b(a)||[]}catch(c){}a=!1;_.Ca(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&tg(this)},tg=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.cc(a.a))}catch(b){}};
var vg=function(a){_.F.call(this);this.a=a;this.h=!1};_.p(vg,_.F);vg.prototype.setEnabled=function(a){this.h=a};var T=function(a){vg.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.J=!0;this.j=10;this.b=null;this.c=!1};_.p(T,vg);T.prototype.Eb=function(a){this.J=a;return this};T.prototype.setUseLocalStorage=T.prototype.Eb;T.prototype.Dc=function(a){this.j=Math.min(a,100);return this};T.prototype.setMaxErrorsPerHour=T.prototype.Dc;T.prototype.Cb=function(a){this.o=a;return this};T.prototype.setGlobalSampling=T.prototype.Cb;T.prototype.tb=function(a,b){this.m[a]=b;return this};
T.prototype.addPerErrorMessageSampling=T.prototype.tb;T.prototype.Bb=function(a){this.O=a;return this};T.prototype.setCallback=T.prototype.Bb;T.prototype.Cc=function(a){this.g=a;return this};T.prototype.setClientId=T.prototype.Cc;T.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.v.bind(this);this.setEnabled(!0);return!0};T.prototype.enable=T.prototype.enable;
T.prototype.yb=function(a,b,c,d,e){var f=_.Af(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.za(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var l=100,n=0;n<h.length;++n){var t=h[n];(new RegExp(t)).test(a)&&(l=this.m[t])}if(h=(100*Math.random()).toFixed(6)>=this.o*l/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new ug(this.j,this.J));if(null===this.b)h=0;else{a:{h=this.b;l=(0,_.sa)();if(h.a.length==h.g)if(h.a[0]<l-36E5)h.a.shift();else{h=!1;break a}h.a.push(l);
tg(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.qb(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,l="Other",Ab?l="Opera":_.w?l="Internet Explorer":Sb?l="Firefox":Wb?l="Chrome":Xb&&(l="Safari"),h.browser=l,h.browser_version=_.Wf,h.os=_.v("CrOS")?"Chrome OS":_.v("Linux")?"Linux":_.wb()?"Windows":_.v("Android")?"Android":ub()?"iPhone":_.v("iPad")?"iPad":_.v("iPod")?"iPod":_.vb()?"Mac":"Unknown",l=_.jb,n="",_.wb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(l=n.exec(l))?l[1]:"0.0"):ub()||_.v("iPad")||
_.v("iPod")?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(l=n.exec(l))&&l[1].replace(/_/g,".")):_.vb()?(n=/Mac OS X ([0-9_.]+)/,n=(l=n.exec(l))?l[1].replace(/_/g,"."):"10"):_.v("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(l=n.exec(l))&&l[1]):_.v("CrOS")&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(l=n.exec(l))&&l[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ja(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,b=
wg(h),e=null!=e?_.Ua(e.stack):"",_.Ja(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),xg(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ua(this.a.a),_.Ja(a)||(f.version=a),xg(this,"https://clients2.google.com/cr/staging_perf",wg(f)))};T.prototype.reportError=T.prototype.yb;T.prototype.v=function(a,b,c,d,e){this.yb(a,b,c,d,e);null!=this.l&&_.za(this.l)&&this.l(a,b,c,d,e)};
var wg=function(a){var b="",c;for(c in a)b+=_.Ja(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},xg=function(a,b,c,d){d=d||"";var e=_.Ja(d)?{}:{"Content-Type":"text/plain"};_.Ke(b+c,a.H.bind(a,b),"POST",d,e,6E4,!0)};T.prototype.H=function(a,b){_.Ue(b.target)};
var yg=function(a){vg.call(this,a);this.O=null;this.b=0};_.p(yg,vg);yg.prototype.Bb=function(a){this.O=a;return this};var zg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];yg.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.Be(6E4);_.I(this,a);var b=new _.N(this);_.I(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
yg.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<zg.length;++b)if(this.b==zg[b].age){a=zg[b].name;break}if(""!=a){var b=Ag.test(_.jb)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.Af(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.Ua(this.a.a);_.Ja(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.za(this.O)&&this.O(b,a[d].displayName,a[d].value);_.Ke("https://clients2.google.com/cr/staging_perf"+c,Bg,"POST","",null,6E4,!0)}}};var Bg=function(a){_.Ue(a.target)},Ag=/(x86_64|Win64)/;
var Cg=function(a){_.F.call(this);this.b=new og(a);this.a={}};_.p(Cg,_.F);_.wa("webmonitoring.Monitoring",Cg);Cg.prototype.setVersion=function(a){this.b.setVersion(a);return this};Cg.prototype.setVersion=Cg.prototype.setVersion;Cg.prototype.Na=function(a){this.b.Na(a);return this};Cg.prototype.setChannel=Cg.prototype.Na;Cg.prototype.ob=function(a){this.b.ob(a);return this};Cg.prototype.setContext=Cg.prototype.ob;Cg.prototype.Ja=function(){null!=this.a[2]||(this.a[2]=new T(this.b));return this.a[2]}; Cg.prototype.createJsErrorsReporter=Cg.prototype.Ja;
var Dg=function(a){Cg.call(this,a)};_.p(Dg,Cg);Dg.prototype.Ja=function(){var a=Dg.A.Ja.call(this);a.c=!0;return a};_.Eg=function(){var a=new Dg("Google_Hangouts_Chrome");a.Na(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new yg(a.b));a.a[1].enable();a.Ja().Eb(!1).Cb(100).tb("Script error.",0).enable()};var Fg=function(a,b){this.g=a;this.b=b;this.constructor.ub||(this.constructor.ub={});this.constructor.ub[this.toString()]=this};Fg.prototype.toString=function(){this.a||(this.a=this.g.a+":"+this.b);return this.a};var Gg=function(a,b){Fg.call(this,a,b)};_.p(Gg,Fg);var Hg=function(a){this.a=a};new Hg("lib");var Ig,Qg,Rg,Sg;_.Jg=function(a){_.F.call(this);this.c={};this.j={};this.l={};this.a={};this.g={};this.H={};this.m=a?a.F():new _.L;this.N=!a;this.b=null;a?(this.b=a,this.l=a.l,this.a=a.a,this.j=a.j,this.g=a.g):(0,_.sa)();a=Ig(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.Jg,_.F);_.Kg=.05>Math.random();Ig=function(a){for(;a.b;)a=a.b;return a};_.Jg.prototype.get=function(a){var b=_.Lg(this,a);if(null==b)throw new Mg(a);return b};
_.Lg=function(a,b){for(var c=a;c;c=c.b){if(c.I)throw Error("v");if(c.c[b])return c.c[b][0];if(c.H[b])break}if(c=a.l[b]){c=c(a);if(null==c)throw Error("w`"+b);_.Ng(a,b,c);return c}return null};
_.Jg.prototype.J=function(a,b){var c=_.Lg(this,a);if(null==c){if(this.g[a]){var d=this.g[a].h();_.Md(d,(0,_.q)(this.J,this,a,b));return d}throw new Og(a,b,"Module loaded but service or factory not registered with app contexts.");}return c.gb?(d=new _.Fd,_.Nd(d,c.gb()),d.b(c),_.Md(d,(0,_.q)(this.o,this,a)),d):this.o(a)};_.Jg.prototype.o=function(a){this.g[a]&&delete this.g[a];return this.get(a)};_.Jg.prototype.G=function(a,b,c){return c instanceof _.Gd?c:new Pg(a,b,c)};
_.Ng=function(a,b,c,d){if(a.I)d||_.H(c);else{a.c[b]=[c,!d];d=Qg(a,a,b);for(var e=0;e<d.length;e++)d[e].b(null);delete a.j[b];return c}};Qg=function(a,b,c){var d=[],e=a.a[c];e&&(_.Za(e,function(a){var c;a:{for(c=a.fb;c;){if(c==b){c=!0;break a}c=c.b}c=!1}c&&(d.push(a.d),_.gb(e,a))}),0==e.length&&delete a.a[c]);return d};Rg=function(a,b){a.a&&Pc(a.a,function(a,d,e){_.Za(a,function(c){c.fb==b&&_.gb(a,c)});0==a.length&&delete e[d]})};
_.Jg.prototype.D=function(a,b){var c=this.a&&this.a[a];if(c){for(var d=0;d<c.length;++d)if(c[d].fb==this&&c[d].d==b){_.fb(c,d);break}0==c.length&&delete this.a[a]}};_.Jg.prototype.w=function(){if(Ig(this)==this){var a=this.h;if(a)for(;a.length;)a[0].$()}else for(var a=Ig(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&a[0].$&&a[0].$();this.c=null;this.N&&this.m.$();Rg(this,this);this.a=null;_.H(this.M);this.H=this.M=null;_.Jg.A.w.call(this)};
_.Jg.prototype.F=function(){return this.m};var Mg=function(a){_.Fa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.p(Mg,_.Fa);var Pg=function(a,b,c){_.Fa.call(this);this.message='Module "'+b+'" failed to load when requesting the service "'+a+'" [cause: '+c+"]";this.stack=c.stack+"\nWRAPPED BY:\n"+this.stack};_.p(Pg,_.Fa);var Og=function(a,b,c){_.Fa.call(this);this.message='Configuration error when loading the module "'+b+'" for the service "'+a+'": '+c};_.p(Og,_.Fa); Sg=new Hg("fva");_.Tg=new Gg(Sg,1);

}catch(e){_._DumpException(e)}
try{
var Op=/\s*;\s*/,Pp=function(){return[]},Qp=function(a){a=(a.a.cookie||"").split(Op);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}},Rp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.aa[c[0]].prototype[a].apply(this,arguments)}:b[a].$b?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];if(f=f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Zb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]],f=f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].oc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d)}}:
e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var t=this.a[c[f]];e.push(t?t[a].apply(t,d):this.aa[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].$b||b[a].Zb||b[a].oc?e=null:e=Pp;return e},Sp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},Tp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Ba(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},
Up=[1],Vp=function(a,b){return a.g.get(b)},Wp=function(a){this.a=a||{cookie:""}};_.g=Wp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("p`"+a);if(/[;\r\n]/.test(b))throw Error("q`"+b);_.m(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.sa)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Op),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.m(this.get(a));this.set(a,"",0,b,c);return d};_.g.V=function(){return Qp(this).keys};_.g.S=function(){return Qp(this).values};_.g.clear=function(){for(var a=Qp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Xp=function(a){return this.jb.c(a)},Yp=function(a){_.z(this,a,"ci:ec",null,null)};
_.p(Yp,_.y);Yp.messageId="ci:ec";
var Zp={Jc:_.ff,Rc:_.gf,Mc:_.hf,Nc:_.jf,Lc:_.kf,Tc:_.lf},$p=function(a){var b=a.na,c=function(a){c.A.constructor.call(this,a);var b=this.aa.length;this.a=[];for(var d=0;d<b;++d)this.aa[d].Yc||(this.a[d]=new this.aa[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.na){b.aa&&Tp(d,b.aa);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.za(e[f])&&e[f]!==b){var h=!!e[f].Yb,l=Sp(f,e,d,h);(h=Rp(f,e,l,h))&&(c.prototype[f]=h)}}a=a.A&&a.A.constructor}c.prototype.aa=d;return c},aq=function(a){_.z(this,a,"capi:r_rstr",
null,null)};_.p(aq,_.y);aq.messageId="capi:r_rstr";var bq=function(a){_.z(this,a,"capi:r_recl",null,null)};_.p(bq,_.y);bq.messageId="capi:r_recl";var cq=function(a){_.z(this,a,"capi:r_clre",null,null)};_.p(cq,_.y);cq.messageId="capi:r_clre";var dq=function(a){_.z(this,a,0,Up,null)};_.p(dq,_.y);var eq=function(a){_.z(this,a,"uv_r_hrd",null,null)};_.p(eq,_.y);eq.messageId="uv_r_hrd";var fq=function(a){_.z(this,a,"uv_r_rrr",null,null)};_.p(fq,_.y);fq.messageId="uv_r_rrr";
var gq=function(a){_.z(this,a,"uv_r_rdr",null,null)};_.p(gq,_.y);gq.messageId="uv_r_rdr";
var hq=function(a,b,c){if(!this.jb){for(var d=this.constructor;d&&!d.na;)d=d.A&&d.A.constructor;d.na.wb||(d.na.wb=$p(d));this.jb=new d.na.wb(this);this.c||(this.c=Xp)}var e=this.jb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ha(e,"https://talkgadget.google.com/talkgadget/")){var d=(new Wp(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.eb(f,d)&&h.test(d)&&(e=_.Af(e),
e=_.Af("https://"+d+e.a).toString())}this.la=e;this.g=c||new Yp;a.notificationsOnly&&_.B(this.g,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=Vp(new _.P(window.location.href),"authuser"),null!=c&&(this.b=c));this.m=a.clientUrl||"notifierclient";c=Vp(_.Af(this.m),"authuser");null!=c&&(this.b=c);this.cb=a.propertyName||"Google Talk";this.J=a.cssUrl;this.locale=a.locale;this.C=a.debug;this.Ha=a.userJid;this.Ea=a.uiVersion;this.hc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.X=a.hostLogMinValue;
this.va=a.hideChat;this.ac=a.refresh;this.M=a.hideProfileCard;this.U=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.N=a.hideRecentConversations;this.K=a.hideOTR;this.eb=a.hostServerMessageCallback||!1;this.Z=a.isCentralRoster;this.ib=a.isFullFrame||!1;this.gc=a.rosterClass||"talk_roster";this.jc=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.ua=a.parentToken;
this.dc=b||!1;this.h=_.m(a.isRtl)?a.isRtl:_.qc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Zp)b.push(_.D(Zp[l]))}this.v=a.entityId;this.Fa=a.useQuasarPanels||!1;this.wa=a.silent||!1;this.hb=a.ignoreCentralRoster||!1;this.cc=a.lazy||!1;this.Qa=a.handleProfileLinks||!1;this.Y=a.hostSettings;this.l=a.screen;this.H=a.docsConfig;this.bc=a.jsmode;this.ta=a.moleWidth;this.ga=a.moleHeight;this.fa=a.minimizedMoleHeight||36;this.kc=a.derp;this.Da=window.location.protocol+
"//"+window.location.host;this.j="";this.G=a.optOutAllowed;this.D=a.legacyTalkSignedIn;this.Ga=a.useSpareMole;this.o=a.conversationId};hq.na=_.cf;var iq=function(a){_.z(this,a,0,null,null)};_.p(iq,_.y);var jq=function(a){_.z(this,a,0,null,null)};_.p(jq,_.y);var kq=function(a){_.z(this,a,0,null,null)};_.p(kq,_.y);var lq=function(a){_.z(this,a,0,null,null)};_.p(lq,_.y);var mq=function(a){_.z(this,a,"h_cc",null,null)};_.p(mq,_.y);mq.messageId="h_cc";
var nq=function(a,b){_.td(a,null,b,void 0)},oq=function(a,b,c){_.Ad(a,b,c,null)||_.hd(_.xa(b,a))},pq=function(a){return new _.md(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],oq(n,_.xa(f,l),h);else b(e)})};
var qq=function(a){this.a=a;_.w||(delete this.a.lpu,delete this.a.ppu)},rq=["cn","tp"],sq=function(a,b){var c;if(_.za(window.document.postMessage)||_.za(window.postMessage)||_.w&&window.postMessage)c=1;else if(_.Cb)c=2;else{var d;if(d=_.w){d=!1;try{c=window.opener,window.opener={},d=_.yb(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new qq(d)};_.wa("GTalk_IFrameChannelConfig.build",sq);
var tq=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.g=new _.N(this);_.I(this,this.g);var f=_.jb;d=new _.P(a.la+a.m);_.jc(a.g,2,!1)||(_.Q(d,"ts","0"),_.Q(d,"re",a.hc),_.Q(d,"ref",a.ac));_.Q(d,"client","sm");_.Q(d,"prop",a.cb);_.Q(d,"nav","true");_.Q(d,"fid",a.a);a.C&&_.Q(d,"debug",a.C);_.Q(d,"os",_.Fb);_.Q(d,"stime",c);a.va&&_.Q(d,"hc",a.va);for(c=0;c<rq.length;++c);b=_.cc(b.a);_.Q(d,"xpc",b);_.Q(d,"ec",_.cc(_.D(a.g)));a.l&&_.Q(d,"screen",a.l);-1!=f.indexOf("MSIE")&&_.Q(d,
"ua",f);a.ua&&_.Q(d,"pvt",a.ua);a.eb&&_.Q(d,"hsmc","true");_.m(a.X)&&_.Q(d,"logl",a.X);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.Q(d,"href",b.join("?")));b=new _.P(window.location.href);"false"==Vp(b,"uacheck")&&_.Q(d,"uacheck",!1);(f=a.bc)&&_.Q(d,"jsmode",f);(f=Vp(b,"cssmode"))&&_.Q(d,"cssmode",f);(f=Vp(b,"convid"))&&_.Q(d,"convid",f);if(f=b.g.S("convp"))_.Ca(f)||(f=[String(f)]),_.Gf(d.g,"convp",f);(f=Vp(b,"smexp"))&&_.Q(d,"smexp",
f);f=b.g.S("mods");a.cc&&f.push("lazy");e&&(f=_.hb(f,e));0<f.length&&_.Q(d,"mods",f.join(","));if(!a.la||0>a.la.indexOf("/u/"))(e=Vp(b,"authuser"))?_.Q(d,"authuser",e):null!=a.b&&_.Q(d,"authuser",a.b);e=Vp(b,"eid");_.Ja(_.Ua(e))||_.Q(d,"eid",e);_.Ja(_.Ua(this.a.v))||_.Q(d,"eid",this.a.v);null!=this.a.position&&_.Q(d,"pos",this.a.position);_.m(a.Ea)&&_.Q(d,"uiv",this.a.Ea);a.J&&_.Q(d,"css",a.J);e=a.locale||Vp(b,"hl");null!=e&&_.Q(d,"hl",e);_.m(a.Ha)&&_.Q(d,"uj",a.Ha);null!=a.M&&_.Q(d,"hpc",a.M);null!=
a.U&&_.Q(d,"hsm",a.U);null!=a.T&&_.Q(d,"hro",a.T);null!=a.N&&_.Q(d,"hrc",a.N);null!=a.K&&_.Q(d,"hotr",a.K);null!=a.Z&&_.Q(d,"pop",a.Z);a.dc&&_.Q(d,"pal","1");null!=a.Fa&&_.Q(d,"uqp",a.Fa);null!=a.G&&_.Q(d,"gooa",a.G);null!=a.D&&_.Q(d,"gltsi",a.D);null!=a.Ga&&_.Q(d,"gusm",a.Ga);null!=a.wa&&_.Q(d,"sl",a.wa);a.hb&&_.Q(d,"icr","1");a.Qa&&_.Q(d,"hpl","1");a.Y&&_.Q(d,"hs",a.Y);a.H&&_.Q(d,"dc",_.cc(_.D(a.H)));null!=a.ta&&_.Q(d,"molew",a.ta);null!=a.ga&&_.Q(d,"moleh",a.ga);null!=a.fa&&_.Q(d,"mmoleh",a.fa);
a.kc&&_.Q(d,"derp","1");a.j&&_.Q(d,"fcho",a.j);null!=a.Da&&_.Q(d,"two",a.Da);null!=a.o&&_.Q(d,"convid",a.o);_.Q(d,"host","1");_.Q(d,"zx",_.Va());this.c=d.toString()};_.p(tq,_.F);
var uq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.gc,a.b.body.appendChild(e));a=(0,_.q)(function(){var a="";this.a.ib||(a="height:400px");var b=this.b.createElement("iframe");_.Bc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.zc("talk_loading_msg",e)||_.Ec(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.Ye(this.g,l,["load","error"],function(a){l.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});l.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var vq=new _.O("q"),wq=new _.O("r");var xq=function(a){_.L.call(this);this.a=a.get(wq);a=new _.N(this);_.I(this,a);a.listen(this.a.F(),"uv_r_frm",this.b);a.listen(this.a.F(),"uv_r_rdm",this.c)};_.p(xq,_.L);xq.prototype.reload=function(a){var b=new _.Jf;_.B(b,1,a);this.a.sendMessage(b)};xq.prototype.b=function(a){a=new _.Kf(a.P);_.M(this,new yq(!!_.A(a,1)))};xq.prototype.c=function(a){a=new _.If(a.P);_.M(this,new zq(_.A(a,1)))};var yq=function(a){_.K.call(this,"uv_r_frm");this.a=a};_.p(yq,_.K); var zq=function(a){_.K.call(this,"uv_r_rdm");this.a=a};_.p(zq,_.K);
var Aq=function(a){var b=_.k.GTalkNotifier;return b?_.qd(b):new _.md(function(c,d){var e=_.Ce(function(){return d("chat.host.Client is not available!")},25E3),f=window.document.createElement("SCRIPT");f.src=_.Uf(a);f.addEventListener("load",function(){_.De(e);(b=_.k.GTalkNotifier)?c(b):d("chat.host.Client is not available!")});f.addEventListener("error",function(){_.De(e);d("chat.host.Client is not available!")});window.document.body.appendChild(f)})};
var Bq=function(a){_.L.call(this);this.a=a.get(_.S);a=new _.N(this);_.I(a,a);a.listen(this.a.F(),"capi:r_clre",this.h);a.listen(this.a.F(),"capi:r_rrst",this.b);a.listen(this.a.F(),"capi:r_rers",this.c)};_.p(Bq,_.L);Bq.prototype.h=function(a){a=new cq(a.P);_.M(this,new Cq(_.C(a,dq,1)))};Bq.prototype.c=function(){_.M(this,"I")};Bq.prototype.b=function(){_.M(this,"H")};var Cq=function(a){_.K.call(this,"G");this.a=a};_.p(Cq,_.K);
var Dq=function(a){_.N.call(this);this.b=a.get(_.Qf);this.a=a.get(vq);this.listen(this.a,"uv_r_rdm",this.Wb);this.listen(this.a,"uv_r_frm",this.Vb);this.listen(this.b,"G",this.xc);this.listen(this.b,"H",this.Ub);this.listen(this.b,"I",this.Xb)};_.p(Dq,_.N);_.g=Dq.prototype;_.g.xc=function(a){a=(a=a.a)?[_.D(a)]:[void 0];this.a.reload(a)};_.g.Ub=function(){var a=this.a,b=new gq;a.a.sendMessage(b)};_.g.Vb=function(a){var b=this.b;a=!!a.a;var c=new bq;_.B(c,1,!!a);b.a.sendMessage(c)}; _.g.Wb=function(a){if(a.a&&(a=a.a[0])){a=new dq(a);var b=this.b,c=new aq;_.E(c,1,a);b.a.sendMessage(c)}};_.g.Xb=function(){var a=this.a,b=new fq;a.a.sendMessage(b)};
var Eq=function(a){var b=_.Bf(_.A(a,2),"/webchat/extension-start");_.A(a,5)&&_.Q(b,"e",_.A(a,5));return new _.md(function(a,d){_.Ke(b,function(b){_.Ue(b.target)||d();try{var c=JSON.parse(_.Ve(b.target));a(new _.Sf(c))}catch(h){d(h.message)}})})};var Fq=function(a){_.K.call(this,a[0]);this.P=a};_.p(Fq,_.K);var Hq=function(a,b){_.F.call(this);this.m=(0,_.sa)();var c={},d=_.jc(a,1,"hangouts.google.com"),e="";0>d.indexOf("://")&&(e="https://",0<=d.indexOf(":")&&23!=_.A(a,2)&&27!=_.A(a,2)&&(e="http://"));-1!=d.indexOf("talkgadget.")?(c.clientBaseUrl=e+d+"/talkgadget/_/",c.clientUrl="chat"):(c.clientBaseUrl=e+d+"/webchat/u/"+_.jc(a,8,"0")+"/",c.clientUrl="load");c.authUser=_.jc(a,8,"0");c.propertyName=_.Hf(_.A(a,2));c.locale=_.A(a,4);c.hideProfileCard=!0;c.parentToken=_.A(a,3);c.isRtl=_.jc(a,6,!1);c.lazy=
_.jc(a,7,!1);c.entityId=_.A(a,9);c.hostSettings=_.A(a,5);c.jsmode=_.A(a,11);c.isFullFrame=_.jc(a,13,!1);c.rosterId=_.jc(a,12,"talk_roster");c.rosterIframeIdB=_.jc(a,15,"gtn-roster-iframe-id-b");c.derp=!!_.jc(a,16,!1);d=_.C(a,iq,14);null!=d&&(c.isCentralRoster=_.jc(d,1,!1),c.useQuasarPanels=_.jc(d,2,!1));d=_.C(a,lq,10);null!=d&&(c.moleManagerLeftMargin=_.A(d,1),c.moleManagerMiddleMargin=_.A(d,2),c.moleManagerRightMargin=_.A(d,3),c.moleManagerNoMoleAreaMargin=_.A(d,4),c.moleManagerBoundingElementId=
_.A(d,5),c.moleWidth=_.A(d,6),c.moleHeight=_.A(d,7),c.minimizedMoleHeight=_.A(d,8));d=_.C(a,kq,18);null!=d&&(c.optOutAllowed=_.jc(d,1,!0),e=_.C(d,jq,3),null!=e&&(c.legacyTalkSignedIn=_.jc(e,1,!0)),d=_.A(d,4),null!=d&&(c.useSpareMole=d));c.uiVersion=2;c.hideStatusMsgs=!0;c.hideRecentConversations=!0;d=new Yp;_.B(d,2,!0);_.B(d,1,!0);_.B(d,3,!1);c.endpointConfig=d;c.ignoreAutomatedRoster=_.jc(a,17,!1);c.conversationId=_.A(a,19);this.c=c;a=this.a=new hq(this.c,!0,this.c.endpointConfig);var f=this.a.la,
c=this.a.b;if(-1!=f.indexOf("talkgadget."))if(d=_.Af(f),e=d.a,0<=e.indexOf("/u/"))c=f;else{f=e.lastIndexOf("_/");if(0>f||f!=e.length-2)e+="_/";d.a="/u/"+c+e;c=d.toString()}else c=f;a.la=c;this.a.j=window.location.origin;this.b=null;this.l=new _.L;a=_.qb(this.c);a.endpointConfig=_.D(this.a.g);this.h=new b(a,!0);this.j=new _.ig;_.I(this,this.j);Gq(this)};_.p(Hq,_.F);Hq.prototype.sendMessage=function(a){this.xa(_.D(a))};Hq.prototype.xa=function(a){this.g("_h",a)};
Hq.prototype.pb=function(a){this.b=a;_.G(this,function(){this.b=null},this)};Hq.prototype.F=function(){return this.l};var Gq=function(a){var b=sq(a.a.la,a.a.a),b=new tq(a.a,b,a.m,window.document);_.I(a,b);uq(b,a.a.jc,function(){},function(){return Iq(a)})},Iq=function(a){_.mg(a.j,window.document.getElementById(a.a.a).contentWindow,"31ACFC0_","google.com");a.g("_addClientMessageCallback",function(b){a.b&&a.b.xa(b);_.M(a.l,new Fq(b))});a.g("_rosterIframeLoaded")}; Hq.prototype.g=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.h[a]&&this.h[a].apply(this.h,c)};
var Kq=function(){_.N.call(this);_.R("Starting ...");this.a=new _.Jg;_.I(this,this.a);this.h=null;this.c=[];this.listen(window,"unload",this.$);this.b=new _.Lf(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));var a=_.A(this.b,1),b=new _.ig;_.kg(b);b.a=new _.cg((0,_.q)(b.D,b),a);b.a.ca("*",void 0,void 0);b.c.push(_.xa(_.H,b.a));this.g=b;_.Ng(this.a,wq,this.g);Jq(this)},Lq;_.p(Kq,_.N);
var Jq=function(a){_.R("Initializing ...");nq(pq([Eq(a.b).then(a.j,void 0,a),Aq(a.b)]).then(function(b){_.ga();var c=b[window.Symbol.iterator];b=c?c.call(b):_.fa(b);var d=b.next().value;b=b.next().value;if(a.I)b=null;else{var c=new mq,e=_.Af(_.A(a.b,2)),f=e.b;null!=e.c&&(f+=":"+e.c);_.B(c,1,f);_.B(c,2,27);_.B(c,13,!0);_.B(c,17,!0);d=_.A(d,1);_.B(c,3,d);d=_.A(a.b,4);_.B(c,11,d);d=_.A(a.b,3)||"en";_.B(c,4,d);d=new iq;_.B(d,2,!0);_.B(d,1,!0);_.E(c,14,d);b=new Hq(c,b)}return b}).then(function(b){if(!a.I){b.pb(a.g);
a.g.pb(b);a.h=b;_.Ng(a.a,_.S,a.h);b=new xq(a.a);_.Ng(a.a,vq,b);_.Ng(a.a,_.Qf,new Bq(a.a));new Dq(a.a);for(a.g.sendMessage(new eq);a.c.length;)a.c.shift()();a.c=null}}),function(a){_.R("Failed to start : %s.",a||"")})};Kq.prototype.j=function(a){var b=this;return new _.md(function(c,d){b.g.sendMessage(a);_.A(a,1)||d("Unauthenticated");c(a)})};_.wa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Eg();if(!_.m(Lq)||null==Lq||Lq.I)Lq=new Kq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
