"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca,ea,da,ha;aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;ca=function(){ca=function(){};ba.Symbol||(ba.Symbol=da)};ea=0;da=function(a){return"jscomp_symbol_"+(a||"")+ea++};
_.ga=function(){ca();var a=ba.Symbol.iterator;a||(a=ba.Symbol.iterator=ba.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return _.fa(this)}});_.ga=function(){}};_.fa=function(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};ha=function(a){_.ga();a={next:a};a[ba.Symbol.iterator]=function(){return this};return a};_.ia=_.ia||{};_.k=this;_.ja="closure_uid_"+(1E9*Math.random()>>>0); _.ka=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var na,oa;_.m=function(a){return void 0!==a};na=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};oa=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.pa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Wc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.qa=function(a,b){a=a.split(".");var c=_.k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.m(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};_.sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?oa:na;return _.q.apply(null,arguments)};
_.ta=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ua=function(a){return"function"==_.pa(a)};_.va=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.wa=function(a){var b=_.pa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.xa=function(a){return"array"==_.pa(a)};_.ya=function(){};_.za=function(a){a=a.split(".");for(var b=_.k,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};
var Aa=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};Aa.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var Ba=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};_.Ca=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Ca);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.Ca,Error);_.Ca.prototype.name="CustomError";var Da;_.Ea=function(a){return function(){return a}}(!1);_.Fa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;var Ga,Ha,Ja,Ia,Ma,Na,La;Ga=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};Ha=function(a){a=String(a);if(Ga(a))try{return eval("("+a+")")}catch(b){}throw Error("b`"+a);};_.Ka=function(a,b){var c=[];Ia(new Ja(b),a,c);return c.join("")};
Ja=function(a){this.a=a};
Ia=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.xa(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],Ia(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),La(d,c),c.push(":"),Ia(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":La(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("c`"+typeof b);}}};Ma={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Na=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; La=function(a,b){b.push('"',a.replace(Na,function(a){var b=Ma[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Ma[a]=b);return b}),'"')};
var Pa,Qa,Ra,Ta;_.Oa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Pa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};Ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.Sa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.Ua=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ta.length;f++)c=Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Va=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Wa=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Xa=function(a){Xa[" "](a);return a};Xa[" "]=_.ya;_.Ya=function(a,b){try{return Xa(a[b]),!0}catch(c){}return!1};_.Za=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var $a=function(){};var db,fb,gb,hb,ib,jb,kb,eb,mb,pb;_.ab=function(a,b){return 0==a.lastIndexOf(b,0)};_.bb=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.cb=function(a){return/^[\s\xa0]*$/.test(a)};db=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.lb=function(a){if(!eb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(fb,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(gb,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(hb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ib,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(jb,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(kb,"&#0;"));return a};fb=/&/g;gb=/</g;hb=/>/g;ib=/"/g;jb=/'/g;kb=/\x00/g;eb=/[\x00&<>"']/;mb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.nb=function(a){return null==a?"":String(a)};_.ob=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.ka)()).toString(36)};
_.qb=function(a,b){var c=0;a=db(String(a)).split(".");b=db(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=pb(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||pb(0==f[2].length,0==h[2].length)||pb(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; pb=function(a,b){return a<b?-1:a>b?1:0};
_.u=function(){this.H=this.H;this.C=this.C};_.u.prototype.H=!1;_.u.prototype.$=function(){this.H||(this.H=!0,this.w())};_.y=function(a,b){_.w(a,_.sa(_.x,b))};_.w=function(a,b,c){a.H?_.m(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.m(c)?(0,_.q)(b,c):b))};_.u.prototype.w=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.x=function(a){a&&"function"==typeof a.$&&a.$()};
var rb="closure_listenable_"+(1E6*Math.random()|0),sb=function(a){return!(!a||!a[rb])},tb=0;a:{var vb=_.k.navigator;if(vb){var wb=vb.userAgent;if(wb){_.ub=wb;break a}}_.ub=""}_.z=function(a){return-1!=_.ub.indexOf(a)};var xb=function(){};xb.prototype.a=null;var zb=function(a){var b;(b=a.a)||(b={},yb(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Bb=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("g");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,l,n,r,v,R){if("%"==r)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("h");arguments[0]=e;return Ab[r].apply(null,arguments)})},Ab={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+mb(" ",Number(c)-a.length):mb(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+mb(" ",a):f+mb(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,l){return Ab.f((0,window.parseInt)(a,10),b, c,d,0,f,h,l)}};Ab.i=Ab.d;Ab.u=Ab.d;
_.A=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Bb("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+Bb(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Bb.apply({},c)))};
var Cb=function(a){this.a=a};new Cb("lib");var Db=function(a,b){this.g=a;this.b=b;this.constructor.vb||(this.constructor.vb={});this.constructor.vb[this.toString()]=this};Db.prototype.toString=function(){this.a||(this.a=this.g.a+":"+this.b);return this.a};_.B=function(a,b,c){this.g=a;this.b=b||null;this.a=c||[]};_.B.prototype.toString=function(){return this.g};var Eb=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};Eb.prototype.setVersion=function(a){this.c=a;return this};Eb.prototype.Na=function(a){this.a=a;return this};Eb.prototype.pb=function(a){this.g=_.Sa(a);return this};var Fb;Fb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.C=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Gb=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.Hb=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var n=h[l];b.call(c,n,l,a)&&(e[f++]=n)}return e};
_.Ib=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};_.Jb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Lb=function(a,b){b=_.Kb(a,b,void 0);return 0>b?null:_.t(a)?a.charAt(b):a[b]};
_.Kb=function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Mb=function(a,b){return 0<=Fb(a,b)};_.Ob=function(a,b){b=Fb(a,b);var c;(c=0<=b)&&_.Nb(a,b);return c};_.Nb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Pb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.Qb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Rb=function(){this.b=this.a=null},Tb=new Aa(function(){return new Sb},function(a){a.reset()},100);Rb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Sb=function(){this.next=this.b=this.a=null};Sb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Sb.prototype.reset=function(){this.next=this.b=this.a=null};
var Xb;_.Ub=[];_.Vb=[];_.Wb=!1;Xb=function(a){_.Ub[_.Ub.length]=a;if(_.Wb)for(var b=0;b<_.Vb.length;b++)a((0,_.q)(_.Vb[b].b,_.Vb[b]))};_.D=function(a,b){this.type="undefined"!=typeof _.Yb&&a instanceof _.Yb?String(a):a;this.b=this.target=b;this.c=!1;this.Ab=!0};_.D.prototype.l=function(){this.c=!0};_.D.prototype.g=function(){this.Ab=!1};var Zb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ma=e;this.key=++tb;this.removed=this.Ia=!1},$b=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ma=null};var ac;ac=function(){return _.z("iPhone")&&!_.z("iPod")&&!_.z("iPad")};_.bc=function(){return _.z("Macintosh")};_.cc=function(){return _.z("Windows")};var dc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ec=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,f=null;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?(0,window.decodeURIComponent)(f.replace(/\+/g," ")):"")}}};
var fc=function(a,b){_.D.call(this,a,b);this.P=b};_.p(fc,_.D);_.E=new _.B("nED8Yb");_.gc=new _.B("xclgJb");_.hc=new _.B("Qz9Lj");var ic=function(){};ic.prototype.c=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var jc=function(a){(a?a:function(){}).Xb=!0};var kc=function(a,b){Db.call(this,a,b)};_.p(kc,Db);var lc=function(a){_.u.call(this);this.a=a;this.h=!1};_.p(lc,_.u);lc.prototype.setEnabled=function(a){this.h=a};var mc=function(a){this.src=a;this.a={};this.b=0},oc=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var l=nc(b,c,e,f);-1<l?(a=b[l],d||(a.Ia=!1)):(a=new Zb(c,a.src,h,!!e,f),a.Ia=d,b.push(a));return a};mc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=nc(e,b,c,d);return-1<b?($b(e[b]),_.Nb(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var pc=function(a,b){var c=b.type;c in a.a&&_.Ob(a.a[c],b)&&($b(b),0==a.a[c].length&&(delete a.a[c],a.b--))};mc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,$b(d[e]);delete this.a[c];this.b--}return b};
var qc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=nc(a,c,d,e));return-1<b?a[b]:null},rc=function(a){var b=_.m(void 0)?"undefined":void 0,c=_.m(b),d=c?b.toString():"",e=_.m(void 0);return Pa(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})},nc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ma==d)return e}return-1};
var sc=function(){return(_.z("Chrome")||_.z("CriOS"))&&!_.z("Edge")};var tc,uc=function(){};_.p(uc,xb);var vc=function(a){return(a=yb(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},yb=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("k");}return a.b};tc=new uc;
var xc;_.wc=function(a){if(a.S&&"function"==typeof a.S)return a.S();if(_.t(a))return a.split("");if(_.wa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Qa(a)};
xc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.wa(a)||_.t(a))(0,_.C)(a,b,void 0);else{var c;if(a.V&&"function"==typeof a.V)c=a.V();else if(a.S&&"function"==typeof a.S)c=void 0;else if(_.wa(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=Ra(a);for(var d=_.wc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.yc=function(){};_.p(_.yc,ic);_.yc.prototype.b=function(a){return a};jc(_.yc.prototype.b);_.yc.prototype.g=function(){return!0};jc(_.yc.prototype.g);var zc,Bc,Cc,Ac;zc=function(a){_.k.setTimeout(function(){throw a;},0)};_.Dc=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));c=Ac(c);!_.ua(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&!_.z("Edge")&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Bc||(Bc=Cc()),Bc(c)):_.k.setImmediate(c)};
Cc=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.z("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.z("Trident")&&!_.z("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.wb;c.wb=null;a()}};return function(a){d.next={wb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};Ac=function(a){return a};Xb(function(a){Ac=a});
_.Fc=function(){this.a="";this.g=_.Ec;this.b=null};_.Fc.prototype.lb=!0;_.Fc.prototype.Ka=function(){return this.b};_.Fc.prototype.mb=!0;_.Fc.prototype.kb=function(){return this.a};_.Ec={};_.Gc=function(a,b){var c=new _.Fc;c.a=a;c.b=b;return c};_.Gc("<!DOCTYPE html>",0);_.Gc("",0);_.Hc=_.Gc("<br>",0);
var Ic="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},Jc=function(){};Jc.prototype.next=function(){throw Ic;};Jc.prototype.ha=function(){return this};
var Kc=function(a){if(a instanceof Jc)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.wa(a)){var b=0,c=new Jc;c.next=function(){for(;;){if(b>=a.length)throw Ic;if(b in a)return a[b++];b++}};return c}throw Error("l");},Lc=function(a,b){if(_.wa(a))try{(0,_.C)(a,b,void 0)}catch(c){if(c!==Ic)throw c;}else{a=Kc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==Ic)throw c;}}},Mc=function(a){if(_.wa(a))return _.Qb(a);a=Kc(a);var b=[];Lc(a,function(a){b.push(a)});return b};
var Nc,Oc,Rc,Vc,Wc,$c,ad,cd;Nc=_.z("Opera");_.F=_.z("Trident")||_.z("MSIE");Oc=_.z("Edge");_.Pc=_.z("Gecko")&&!(-1!=_.ub.toLowerCase().indexOf("webkit")&&!_.z("Edge"))&&!(_.z("Trident")||_.z("MSIE"))&&!_.z("Edge");_.Qc=-1!=_.ub.toLowerCase().indexOf("webkit")&&!_.z("Edge");Rc=_.k.navigator||null;_.Sc=Rc&&Rc.platform||"";_.Tc=_.bc();_.Uc=_.cc();Vc=function(){var a=_.k.document;return a?a.documentMode:void 0};
a:{var Xc="",Yc=function(){var a=_.ub;if(_.Pc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Oc)return/Edge\/([\d\.]+)/.exec(a);if(_.F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Qc)return/WebKit\/(\S+)/.exec(a);if(Nc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Yc&&(Xc=Yc?Yc[1]:"");if(_.F){var Zc=Vc();if(null!=Zc&&Zc>(0,window.parseFloat)(Xc)){Wc=String(Zc);break a}}Wc=Xc}$c=Wc;ad={};_.bd=function(a){return _.Za(ad,a,function(){return 0<=_.qb($c,a)})};var dd=_.k.document; cd=dd&&_.F?Vc()||("CSS1Compat"==dd.compatMode?(0,window.parseInt)($c,10):5):void 0;
_.ed=new _.B("pVbxBc");var fd,gd,hd,id,kd;_.jd=function(a,b){fd||gd();hd||(fd(),hd=!0);var c=id,d=Tb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d};gd=function(){if(-1!=String(_.k.Promise).indexOf("[native code]")){var a=_.k.Promise.resolve(void 0);fd=function(){a.then(kd)}}else fd=function(){_.Dc(kd)}};hd=!1;id=new Rb;kd=function(){for(var a;a=id.remove();){try{a.a.call(a.b)}catch(b){zc(b)}Ba(Tb,a)}hd=!1};
var ld=!_.F||9<=Number(cd);!_.Pc&&!_.F||_.F&&9<=Number(cd)||_.Pc&&_.bd("1.9.1");_.F&&_.bd("9");var md=!_.F||9<=Number(cd),nd=_.F&&!_.bd("9");!_.Qc||_.bd("528");_.Pc&&_.bd("1.9b")||_.F&&_.bd("8")||Nc&&_.bd("9.5")||_.Qc&&_.bd("528");_.Pc&&!_.bd("8")||_.F&&_.bd("9");var od=function(){};_.p(od,$a);od.prototype.clear=function(){var a=Mc(this.ha(!0)),b=this;(0,_.C)(a,function(a){b.remove(a)})};_.G=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.G?(c=a.V(),d=a.S()):(c=Ra(a),d=Qa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.G.prototype.S=function(){pd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.G.prototype.V=function(){pd(this);return this.a.concat()};_.rd=function(a,b){return qd(a.b,b)};
_.G.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.G.prototype.remove=function(a){return qd(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&pd(this),!0):!1};var pd=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];qd(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],qd(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.G.prototype.get=function(a,b){return qd(this.b,a)?this.b[a]:b};
_.G.prototype.set=function(a,b){qd(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.G.prototype.forEach=function(a,b){for(var c=this.V(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.G.prototype.ha=function(a){pd(this);var b=0,c=this.c,d=this,e=new Jc;e.next=function(){if(c!=d.c)throw Error("m");if(b>=d.a.length)throw Ic;var e=d.a[b++];return a?e:d.b[e]};return e};var qd=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var sd=_.z("Firefox"),td=ac()||_.z("iPod"),ud=_.z("iPad"),vd=_.z("Android")&&!(sc()||_.z("Firefox")||_.z("Opera")||_.z("Silk")),wd=sc(),xd=_.z("Safari")&&!(sc()||_.z("Coast")||_.z("Opera")||_.z("Edge")||_.z("Silk")||_.z("Android"))&&!(ac()||_.z("iPad")||_.z("iPod"));
var yd=null;var Ed,Hd,Gd;_.Bd=function(a){return a?new _.zd(_.Ad(a)):Da||(Da=new _.zd)};_.Dd=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.Cd(window.document,"*",a,b)[0];return d||null};
_.Cd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.Mb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Fd=function(a,b){_.Oa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Ed.hasOwnProperty(d)?a.setAttribute(Ed[d],b):_.ab(d,"aria-")||_.ab(d,"data-")?a.setAttribute(d,b):a[d]=b})};Ed={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
Hd=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.wa(f)||_.ta(f)&&0<f.nodeType?d(f):(0,_.C)(Gd(f)?_.Qb(f):f,d)}};_.Id=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Ad=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};Gd=function(a){if(a&&"number"==typeof a.length){if(_.ta(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ua(a))return"function"==typeof a.item}return!1};
_.zd=function(a){this.a=a||_.k.document||window.document};_.g=_.zd.prototype;_.g.ya=_.Bd;_.g.B=function(a){return _.t(a)?this.a.getElementById(a):a};
_.g.ma=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!ld&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.lb(h.name),'"');if(h.type){f.push(' type="',_.lb(h.type),'"');var l={};_.Ua(l,h);delete l.type;h=l}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.t(h)?f.className=h:_.xa(h)?f.className=h.join(" "):_.Fd(f,h));2<e.length&&Hd(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var Jd=function(a,b){_.D.call(this,a?a.type:"");this.b=this.target=null;this.keyCode=0;this.C=this.m=this.h=this.j=!1;this.a=this.state=null;a&&(this.type=a.type,this.target=a.target||a.srcElement,this.b=b,(b=a.relatedTarget)&&_.Pc&&_.Ya(b,"nodeName"),this.keyCode=a.keyCode||0,this.j=a.ctrlKey,this.h=a.altKey,this.m=a.shiftKey,this.C=a.metaKey,this.state=a.state,this.a=a,a.defaultPrevented&&this.g())};_.p(Jd,_.D);
Jd.prototype.l=function(){Jd.A.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Jd.prototype.g=function(){Jd.A.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,nd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Md,Nd,Od,Ud,Yd,Kd,ae,Xd,Vd;_.Ld=function(a,b){this.a=0;this.C=void 0;this.c=this.b=this.g=null;this.h=this.j=!1;if(a!=_.ya)try{var c=this;a.call(b,function(a){Kd(c,2,a)},function(a){Kd(c,3,a)})}catch(d){Kd(this,3,d)}};Md=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};Md.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};Nd=new Aa(function(){return new Md},function(a){a.reset()},100);Od=function(a,b,c){var d=Nd.get();d.h=a;d.b=b;d.c=c;return d};
_.Pd=function(a){if(a instanceof _.Ld)return a;var b=new _.Ld(_.ya);Kd(b,2,a);return b};_.Rd=function(){var a,b=new _.Ld(function(b){a=b});return new Qd(b,a)};_.Ld.prototype.then=function(a,b,c){return _.Sd(this,_.ua(a)?a:null,_.ua(b)?b:null,c)};Va(_.Ld);_.Ld.prototype.cancel=function(a){0==this.a&&_.jd(function(){var b=new Td(a);Ud(this,b)},this)};
Ud=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?Ud(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):Vd(c),Wd(c,e,3,b)))}a.g=null}else Kd(a,3,b)};Yd=function(a,b){a.b||2!=a.a&&3!=a.a||Xd(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.Sd=function(a,b,c,d){var e=Od(null,null,null);e.a=new _.Ld(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(r){h(r)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof Td?h(b):a(e)}catch(r){h(r)}}:h});e.a.g=a;Yd(a,e);return e.a};_.Ld.prototype.m=function(a){this.a=0;Kd(this,2,a)};_.Ld.prototype.o=function(a){this.a=0;Kd(this,3,a)};
Kd=function(a,b,c){0==a.a&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.a=1,_.Zd(c,a.m,a.o,a)||(a.C=c,a.a=b,a.g=null,Xd(a),3!=b||c instanceof Td||$d(a,c)))};_.Zd=function(a,b,c,d){if(a instanceof _.Ld)return Yd(a,Od(b||_.ya,c||null,d)),!0;if(Wa(a))return a.then(b,c,d),!0;if(_.ta(a))try{var e=a.then;if(_.ua(e))return ae(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
ae=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(n){l(n)}};Xd=function(a){a.j||(a.j=!0,_.jd(a.l,a))};Vd=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.Ld.prototype.l=function(){for(var a;a=Vd(this);)Wd(this,a,this.a,this.C);this.j=!1};
var Wd=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,be(b,c,d);else try{b.g?b.h.call(b.c):be(b,c,d)}catch(e){ce.call(null,e)}Ba(Nd,b)},be=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},$d=function(a,b){a.h=!0;_.jd(function(){a.h&&ce.call(null,b)})},ce=zc,Td=function(a){_.Ca.call(this,a)};_.p(Td,_.Ca);Td.prototype.name="cancel";var Qd=function(a,b){this.a=a;this.b=b};
var de=function(a){this.a=a};_.p(de,od);_.g=de.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.t(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ha=function(a){var b=0,c=this.a,d=new Jc;d.next=function(){if(b>=c.length)throw Ic;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.t(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var ee,fe,ge,je,le,ue,me,oe,ne,re,pe,ke,ve;_.H=function(a,b){this.b=this.C=this.h="";this.c=null;this.l=this.a="";this.j=!1;var c;a instanceof _.H?(this.j=_.m(b)?b:a.j,ee(this,a.h),this.C=a.C,this.b=a.b,fe(this,a.c),this.a=a.a,ge(this,he(a.g)),_.ie(this,a.l)):a&&(c=String(a).match(dc))?(this.j=!!b,ee(this,c[1]||"",!0),this.C=je(c[2]||""),this.b=je(c[3]||"",!0),fe(this,c[4]),this.a=je(c[5]||"",!0),ge(this,c[6]||"",!0),_.ie(this,c[7]||"",!0)):(this.j=!!b,this.g=new ke(null,0,this.j))};
_.H.prototype.toString=function(){var a=[],b=this.h;b&&a.push(le(b,me,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.C)&&a.push(le(b,me,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(le(c,"/"==c.charAt(0)?ne:oe,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",le(c,pe));return a.join("")};
ee=function(a,b,c){a.h=c?je(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};fe=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("n`"+b);a.c=b}else a.c=null};ge=function(a,b,c){b instanceof ke?(a.g=b,qe(a.g,a.j)):(c||(b=le(b,re)),a.g=new ke(b,0,a.j))};_.I=function(a,b,c){a.g.set(b,c)};_.ie=function(a,b,c){a.l=c?je(b):b};_.se=function(a){return a instanceof _.H?new _.H(a):new _.H(a,void 0)};
_.te=function(a,b){a instanceof _.H||(a=_.se(a));b instanceof _.H||(b=_.se(b));var c=a;a=new _.H(c);var d=!!b.h;d?ee(a,b.h):d=!!b.C;d?a.C=b.C:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)fe(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var c=_.ab(e,"/"),e=e.split("/"),f=[],h=0;h<e.length;){var l=e[h++];"."==l?c&&h==e.length&&f.push(""):".."==l?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(l),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?ge(a,he(b.g)):d=!!b.l;d&&_.ie(a,b.l);return a};je=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};le=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,ue),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};ue=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
me=/[#\/\?@]/g;oe=/[\#\?:]/g;ne=/[\#\?]/g;re=/[\#\?@]/g;pe=/#/g;ke=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};ve=function(a){a.a||(a.a=new _.G,a.b=0,a.g&&ec(a.g,function(b,c){b=(0,window.decodeURIComponent)(b.replace(/\+/g," "));ve(a);a.g=null;b=we(a,b);var d=a.a.get(b);d||a.a.set(b,d=[]);d.push(c);a.b+=1}))};ke.prototype.remove=function(a){ve(this);a=we(this,a);return _.rd(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
ke.prototype.clear=function(){this.a=this.g=null;this.b=0};var xe=function(a,b){ve(a);b=we(a,b);return _.rd(a.a,b)};ke.prototype.V=function(){ve(this);for(var a=this.a.S(),b=this.a.V(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};ke.prototype.S=function(a){ve(this);var b=[];if(_.t(a))xe(this,a)&&(b=_.Pb(b,this.a.get(we(this,a))));else{a=this.a.S();for(var c=0;c<a.length;c++)b=_.Pb(b,a[c])}return b};
ke.prototype.set=function(a,b){ve(this);this.g=null;a=we(this,a);xe(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};ke.prototype.get=function(a,b){a=a?this.S(a):[];return 0<a.length?String(a[0]):b};_.ye=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(we(a,b),_.Qb(c)),a.b+=c.length)};
ke.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.V(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.S(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.g=a.join("&")};
var he=function(a){var b=new ke;b.g=a.g;a.a&&(b.a=new _.G(a.a),b.b=a.b);return b},we=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},qe=function(a,b){b&&!a.c&&(ve(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.ye(this,c,a))},a));a.c=b};
var ze;ze=function(a){return(a=a.exec(_.ub))?a[1]:""};_.Ae=function(){if(sd)return ze(/Firefox\/([0-9.]+)/);if(_.F||Oc||Nc)return $c;if(wd)return ze(/Chrome\/([0-9.]+)/);if(xd&&!(ac()||_.z("iPad")||_.z("iPod")))return ze(/Version\/([0-9.]+)/);if(td||ud){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.ub);if(a)return a[1]+"."+a[2]}else if(vd)return(a=ze(/Android\s+([0-9.]+)/))?a:ze(/Version\/([0-9.]+)/);return""}();
_.Be=function(a){return _.te(a,"/webchat/host-js")};var Ee,Ge,He,Ke;_.J=function(){};_.Ce="function"==typeof window.Uint8Array;_.K=function(a,b,c,d,e){a.b=null;b||(b=c?[c]:[]);a.o=c?String(c):void 0;a.h=0===c?-1:0;a.g=b;a:{if(a.g.length&&(b=a.g.length-1,(c=a.g[b])&&"object"==typeof c&&!_.xa(c)&&!(_.Ce&&c instanceof window.Uint8Array))){a.C=b-a.h;a.c=c;break a}a.C=Number.MAX_VALUE}a.m={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.C?(c+=a.h,a.g[c]=a.g[c]||_.De):a.c[c]=a.c[c]||_.De;e&&e.length&&(0,_.C)(e,_.sa(Ee,a))};_.De=[];
_.L=function(a,b){if(b<a.C){b+=a.h;var c=a.g[b];return c===_.De?a.g[b]=[]:c}c=a.c[b];return c===_.De?a.c[b]=[]:c};_.Fe=function(a,b,c){a=_.L(a,b);return null==a?c:a};_.M=function(a,b,c){b<a.C?a.g[b+a.h]=c:a.c[b]=c};Ee=function(a,b){var c,d;(0,_.C)(b,function(b){var e=_.L(a,b);null!=e&&(c=b,d=e,_.M(a,b,void 0))});return c?(_.M(a,c,d),c):0};_.N=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.L(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};
_.P=function(a,b,c){a.b||(a.b={});var d=c?_.O(c):c;a.b[b]=c;_.M(a,b,d)};Ge=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.xa(c))for(var d=0;d<c.length;d++)c[d]&&_.O(c[d]);else c&&_.O(c)}};_.O=function(a){Ge(a);return a.g};He=_.k.JSON&&_.k.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.J.prototype.j=_.Ce?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!yd){yd={};for(var a=0;65>a;a++)yd[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=yd,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,l=h?this[e+1]:0,n=e+2<this.length,r=n?this[e+2]:0,v=f>>2,f=(f&3)<<4|l>>4,l=(l&15)<<2|r>>6,r=r&63;n||(r=64,h||(l=64));b.push(a[v],a[f],a[l],a[r])}return b.join("")};try{var b=He.call(null,_.O(this),
Ie)}finally{window.Uint8Array.prototype.toJSON=a}return b}:He?function(){return He.call(null,_.O(this),Ie)}:function(){return _.Ka(_.O(this),Ie)};var Ie=function(a,b){if(_.va(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.J.prototype.toString=function(){Ge(this);return this.g.toString()};Ke=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.Je(a[d],b[d]))return!1;return!0};
_.Je=function(a,b){if(a==b)return!0;if(!_.ta(a)||!_.ta(b)||a.constructor!=b.constructor)return!1;if(_.Ce&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],l=b[c];h&&h.constructor==Object&&(d=h,h=void 0);l&&l.constructor==Object&&(e=l,l=void 0);if(!_.Je(h,l))return!1}return d||e?(d=d||{},e=e||{},Ke(d,e)):!0}if(a.constructor=== Object)return Ke(a,b);throw Error("p");};
var Le,Me,Pe,Se,Ue,Ze,Ve,af,$e,We,Te,bf,Re;Le="closure_lm_"+(1E6*Math.random()|0);Me={};Pe=0;_.Qe=function(a,b,c,d,e){if(_.xa(b)){for(var f=0;f<b.length;f++)_.Qe(a,b[f],c,d,e);return null}c=Re(c);return sb(a)?a.listen(b,c,d,e):Se(a,b,c,!1,d,e)};
Se=function(a,b,c,d,e,f){if(!b)throw Error("q");var h=!!e,l=Te(a);l||(a[Le]=l=new mc(a));c=oc(l,b,c,d,e,f);if(c.proxy)return c;d=Ue();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(Ve(b.toString()),d);else throw Error("r");Pe++;return c};Ue=function(){var a=We,b=md?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Xe=function(a,b,c,d,e){if(_.xa(b)){for(var f=0;f<b.length;f++)_.Xe(a,b[f],c,d,e);return null}c=Re(c);return sb(a)?a.La(b,c,d,e):Se(a,b,c,!0,d,e)};_.Ye=function(a,b,c,d,e){if(_.xa(b))for(var f=0;f<b.length;f++)_.Ye(a,b[f],c,d,e);else c=Re(c),sb(a)?a.Pa(b,c,d,e):a&&(a=Te(a))&&(b=qc(a,b,c,!!d,e))&&Ze(b)};
Ze=function(a){if(!_.va(a)&&a&&!a.removed){var b=a.src;if(sb(b))pc(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(Ve(c),d);Pe--;(c=Te(b))?(pc(c,a),0==c.b&&(c.src=null,b[Le]=null)):$b(a)}}};Ve=function(a){return a in Me?Me[a]:Me[a]="on"+a};af=function(a,b,c,d){var e=!0;if(a=Te(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=$e(f,d),e=e&&!1!==f)}return e};
$e=function(a,b){var c=a.listener,d=a.Ma||a.src;a.Ia&&Ze(a);return c.call(d,b)};
We=function(a,b){if(a.removed)return!0;if(!md){var c=b||_.za("window.event");b=new Jd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=af(c[e],a,!0,b),d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=af(c[e],a,!1,b),d=d&&f}return d}return $e(a,new Jd(b,this))}; Te=function(a){a=a[Le];return a instanceof mc?a:null};bf="__closure_events_fn_"+(1E9*Math.random()>>>0);Re=function(a){if(_.ua(a))return a;a[bf]||(a[bf]=function(b){return a.handleEvent(b)});return a[bf]};Xb(function(a){We=a(We)});
var cf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.p(cf,de);/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.df=function(a,b){this.l=[];this.G=a;this.v=b||null;this.j=this.g=!1;this.c=void 0;this.J=this.K=this.o=!1;this.m=0;this.a=null;this.C=0};_.df.prototype.cancel=function(a){if(this.g)this.c instanceof _.df&&this.c.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.G?this.G.call(this.v,this):this.J=!0;this.g||this.D(new _.ef)}};_.df.prototype.I=function(a,b){this.o=!1;ff(this,a,b)};
var ff=function(a,b,c){a.g=!0;a.c=c;a.j=!b;gf(a)},jf=function(a){if(a.g){if(!a.J)throw new hf;a.J=!1}};_.df.prototype.b=function(a){jf(this);ff(this,!0,a)};_.df.prototype.D=function(a){jf(this);ff(this,!1,a)};_.lf=function(a,b,c){_.kf(a,b,null,c)};_.kf=function(a,b,c,d){a.l.push([b,c,d]);a.g&&gf(a)};_.df.prototype.then=function(a,b,c){var d,e,f=new _.Ld(function(a,b){d=a;e=b});_.kf(this,d,function(a){a instanceof _.ef?f.cancel():e(a)});return f.then(a,b,c)};Va(_.df);
_.mf=function(a,b){b instanceof _.df?_.lf(a,(0,_.q)(b.h,b)):_.lf(a,function(){return b})};_.df.prototype.h=function(a){var b=new _.df;_.kf(this,b.b,b.D,b);a&&(b.a=this,this.C++);return b};
var nf=function(a){return(0,_.Jb)(a.l,function(a){return _.ua(a[1])})},gf=function(a){if(a.m&&a.g&&nf(a)){var b=a.m,c=of[b];c&&(_.k.clearTimeout(c.a),delete of[b]);a.m=0}a.a&&(a.a.C--,delete a.a);for(var b=a.c,d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var l=f.call(e||a.v,b);_.m(l)&&(a.j=a.j&&(l==b||l instanceof Error),a.c=b=l);if(Wa(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.o=!0}catch(n){b=n,a.j=!0,nf(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.I,
a,!0),d=(0,_.q)(a.I,a,!1),b instanceof _.df?(_.kf(b,l,d),b.K=!0):b.then(l,d));c&&(b=new pf(b),of[b.a]=b,a.m=b.a)},hf=function(){_.Ca.call(this)};_.p(hf,_.Ca);hf.prototype.message="Deferred has already fired";hf.prototype.name="AlreadyCalledError";_.ef=function(){_.Ca.call(this)};_.p(_.ef,_.Ca);_.ef.prototype.message="Deferred was canceled";_.ef.prototype.name="CanceledError";var pf=function(a){this.a=_.k.setTimeout((0,_.q)(this.g,this),0);this.b=a}; pf.prototype.g=function(){delete of[this.a];throw this.b;};var of={};
var rf;_.Q=function(a){_.u.call(this);this.T=a;this.J={}};_.p(_.Q,_.u);var qf=[];_.Q.prototype.listen=function(a,b,c,d){_.xa(b)||(b&&(qf[0]=b.toString()),b=qf);for(var e=0;e<b.length;e++){var f=_.Qe(a,b[e],c||this.handleEvent,d||!1,this.T||this);if(!f)break;this.J[f.key]=f}return this};_.sf=function(a,b,c,d){rf(a,b,c,d,void 0)};rf=function(a,b,c,d,e,f){if(_.xa(c))for(var h=0;h<c.length;h++)rf(a,b,c[h],d,e,f);else(b=_.Xe(b,c,d||a.handleEvent,e,f||a.T||a))&&(a.J[b.key]=b)};
_.Q.prototype.Pa=function(a,b,c,d,e){if(_.xa(b))for(var f=0;f<b.length;f++)this.Pa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.T||this,c=Re(c),d=!!d,b=sb(a)?qc(a.g,String(b),c,d,e):a?(a=Te(a))?qc(a,b,c,d,e):null:null,b&&(Ze(b),delete this.J[b.key]);return this};_.Q.prototype.removeAll=function(){_.Oa(this.J,function(a,b){this.J.hasOwnProperty(b)&&Ze(a)},this);this.J={}};_.Q.prototype.w=function(){_.Q.A.w.call(this);this.removeAll()};_.Q.prototype.handleEvent=function(){throw Error("s");};
_.S=function(){_.u.call(this);this.g=new mc(this);this.fa=this;this.J=null};_.p(_.S,_.u);_.S.prototype[rb]=!0;_.S.prototype.I=function(a){this.J=a};_.S.prototype.removeEventListener=function(a,b,c,d){_.Ye(this,a,b,c,d)};
_.T=function(a,b){var c,d=a.J;if(d)for(c=[];d;d=d.J)c.push(d);a=a.fa;d=b.type||b;if(_.t(b))b=new _.D(b,a);else if(b instanceof _.D)b.target=b.target||a;else{var e=b;b=new _.D(d,a);_.Ua(b,e)}var e=!0,f;if(c)for(var h=c.length-1;!b.c&&0<=h;h--)f=b.b=c[h],e=f.oa(d,!0,b)&&e;b.c||(f=b.b=a,e=f.oa(d,!0,b)&&e,b.c||(e=f.oa(d,!1,b)&&e));if(c)for(h=0;!b.c&&h<c.length;h++)f=b.b=c[h],e=f.oa(d,!1,b)&&e;return e};_.g=_.S.prototype;_.g.w=function(){_.S.A.w.call(this);this.g&&this.g.removeAll(void 0);this.J=null};
_.g.listen=function(a,b,c,d){return oc(this.g,String(a),b,!1,c,d)};_.g.La=function(a,b,c,d){return oc(this.g,String(a),b,!0,c,d)};_.g.Pa=function(a,b,c,d){return this.g.remove(String(a),b,c,d)};_.g.oa=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,l=f.Ma||f.src;f.Ia&&pc(this.g,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.Ab};
_.tf=function(a,b){_.S.call(this);this.b=a||1;this.a=b||_.k;this.c=(0,_.q)(this.Dc,this);this.h=(0,_.ka)()};_.p(_.tf,_.S);_.g=_.tf.prototype;_.g.ra=!1;_.g.W=null;_.g.setInterval=function(a){this.b=a;this.W&&this.ra?(this.stop(),this.start()):this.W&&this.stop()};
_.g.Dc=function(){if(this.ra){var a=(0,_.ka)()-this.h;0<a&&a<.8*this.b?this.W=this.a.setTimeout(this.c,this.b-a):(this.W&&(this.a.clearTimeout(this.W),this.W=null),_.T(this,"tick"),this.ra&&(this.W=this.a.setTimeout(this.c,this.b),this.h=(0,_.ka)()))}};_.g.start=function(){this.ra=!0;this.W||(this.W=this.a.setTimeout(this.c,this.b),this.h=(0,_.ka)())};_.g.stop=function(){this.ra=!1;this.W&&(this.a.clearTimeout(this.W),this.W=null)};_.g.w=function(){_.tf.A.w.call(this);this.stop();delete this.a}; _.uf=function(a,b,c){if(_.ua(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("t");return 2147483647<Number(b)?-1:_.k.setTimeout(a,b||0)};_.vf=function(a){_.k.clearTimeout(a)};
var wf=function(a){_.K(this,a,"capi_md1571",null,null)};_.p(wf,_.J);wf.messageId="capi_md1571";var xf={sb:0,Jc:1,Hc:2,rb:3,ab:4},yf=function(a){_.K(this,a,0,null,null)};_.p(yf,_.J);_.Af=function(a){_.K(this,a,"h_exts",zf,null)};_.p(_.Af,_.J);var zf=[2];_.Af.messageId="h_exts";var Bf=function(a){_.K(this,a,0,null,null)};_.p(Bf,_.J);var Cf=function(a){_.S.call(this);this.headers=new _.G;this.D=a||null;this.b=!1;this.v=this.a=null;this.M="";this.j=0;this.h="";this.c=this.K=this.m=this.G=!1;this.l=0;this.o=null;this.Z="";this.T=this.U=!1},Df,Ef,Nf,Mf,Jf,Of,Pf;_.p(Cf,_.S);Df=/^https?$/i;Ef=["POST","PUT"];_.Ff=[];_.Gf=function(a,b,c,d,e,f,h){var l=new Cf;_.Ff.push(l);b&&l.listen("complete",b);l.La("ready",l.ga);f&&(l.l=Math.max(0,f));h&&(l.U=h);l.send(a,c,d,e)};Cf.prototype.ga=function(){this.$();_.Ob(_.Ff,this)};
Cf.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.M+"`"+a);b=b?b.toUpperCase():"GET";this.M=a;this.h="";this.j=0;this.G=!1;this.b=!0;this.a=this.D?vc(this.D):vc(tc);this.v=this.D?zb(this.D):zb(tc);this.a.onreadystatechange=(0,_.q)(this.Y,this);try{this.K=!0,this.a.open(b,String(a),!0),this.K=!1}catch(f){Hf(this,f);return}a=c||"";var e=new _.G(this.headers);d&&xc(d,function(a,b){e.set(b,a)});d=_.Lb(e.V(),If);c=_.k.FormData&&a instanceof _.k.FormData;!_.Mb(Ef,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Z&&(this.a.responseType=this.Z);"withCredentials"in this.a&&this.a.withCredentials!==this.U&&(this.a.withCredentials=this.U);try{Jf(this),0<this.l&&((this.T=Kf(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.q)(this.X,this)):this.o=_.uf(this.X,this.l,this)),this.m=!0,this.a.send(a),this.m=!1}catch(f){Hf(this,f)}};
var Kf=function(a){return _.F&&_.bd(9)&&_.va(a.timeout)&&_.m(a.ontimeout)},If=function(a){return"content-type"==a.toLowerCase()};Cf.prototype.X=function(){"undefined"!=typeof _.ia&&this.a&&(this.h="Timed out after "+this.l+"ms, aborting",this.j=8,_.T(this,"timeout"),this.abort(8))};var Hf=function(a,b){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.h=b;a.j=5;Lf(a);Mf(a)},Lf=function(a){a.G||(a.G=!0,_.T(a,"complete"),_.T(a,"error"))};
Cf.prototype.abort=function(a){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,this.j=a||7,_.T(this,"complete"),_.T(this,"abort"),Mf(this))};Cf.prototype.w=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Mf(this,!0));Cf.A.w.call(this)};Cf.prototype.Y=function(){this.H||(this.K||this.m||this.c?Nf(this):this.N())};Cf.prototype.N=function(){Nf(this)};
Nf=function(a){if(a.b&&"undefined"!=typeof _.ia&&(!a.v[1]||4!=Of(a)||2!=Pf(a)))if(a.m&&4==Of(a))_.uf(a.Y,0,a);else if(_.T(a,"readystatechange"),4==Of(a)){a.b=!1;try{if(_.Qf(a))_.T(a,"complete"),_.T(a,"success");else{a.j=6;var b;try{b=2<Of(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+Pf(a)+"]";Lf(a)}}finally{Mf(a)}}};Mf=function(a,b){if(a.a){Jf(a);var c=a.a,d=a.v[0]?_.ya:null;a.a=null;a.v=null;b||_.T(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
Jf=function(a){a.a&&a.T&&(a.a.ontimeout=null);_.va(a.o)&&(_.vf(a.o),a.o=null)};_.Qf=function(a){var b=Pf(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.M).match(dc)[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!Df.test(a?a.toLowerCase():"");c=b}return c};Of=function(a){return a.a?a.a.readyState:0};Pf=function(a){try{return 2<Of(a)?a.a.status:-1}catch(b){return-1}}; _.Rf=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};Xb(function(a){Cf.prototype.N=a(Cf.prototype.N)});
var Tf=function(){for(var a=10,b=Sf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},Sf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var Uf;Uf=function(a,b){var c=new Bf;_.M(c,1,b);_.M(c,2,a);return c};_.Vf=Uf("?",0);_.Wf=Uf("q",1);_.Xf=Uf("<",2);_.Yf=Uf(">",3);_.Zf=Uf("~",4);_.$f=Uf("s",5);_.ag=function(a){_.K(this,a,"uv_r_rdm",null,null)};_.p(_.ag,_.J);_.ag.messageId="uv_r_rdm";_.bg=function(a){_.K(this,a,"uv_r_rr",null,null)};_.p(_.bg,_.J);_.bg.messageId="uv_r_rr";_.cg=function(a){_.K(this,a,"uv_r_frm",null,null)};_.p(_.cg,_.J);_.cg.messageId="uv_r_frm";_.dg=function(a){_.K(this,a,0,null,null)};_.p(_.dg,_.J);
_.eg=function(a,b){_.u.call(this);this.j=b||Tf();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.Q(this);_.y(this,this.h);this.h.listen(window,"message",this.m)};_.p(_.eg,_.u);_.eg.prototype.ca=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.eg.prototype.m=function(a){a=a.a;var b;b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.H(b)).b,b=_.bb(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.t(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.xa(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new wf(c),_.L(c,1)==this.j)){b=_.L(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ca(a.origin,a.source);
1==_.L(c,2)?this.send(2):this.l(c,a)}}};_.eg.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new wf;_.M(b,3,this.j);_.M(b,1,this.a);_.M(b,2,a);var d=JSON.stringify(_.O(b)),e=this.g,f=this.c;_.F?_.uf(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var fg,ng,og,pg;_.gg=function(a){_.u.call(this);this.c={};this.j={};this.l={};this.a={};this.g={};this.I={};this.m=a?a.F():new _.S;this.N=!a;this.b=null;a?(this.b=a,this.l=a.l,this.a=a.a,this.j=a.j,this.g=a.g):(0,_.ka)();a=fg(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.gg,_.u);_.hg=.05>Math.random();fg=function(a){for(;a.b;)a=a.b;return a};_.gg.prototype.get=function(a){var b=_.ig(this,a);if(null==b)throw new jg(a);return b};
_.ig=function(a,b){for(var c=a;c;c=c.b){if(c.H)throw Error("v");if(c.c[b])return c.c[b][0];if(c.I[b])break}if(c=a.l[b]){c=c(a);if(null==c)throw Error("w`"+b);_.kg(a,b,c);return c}return null};
_.gg.prototype.J=function(a,b){var c=_.ig(this,a);if(null==c){if(this.g[a]){var d=this.g[a].h();_.lf(d,(0,_.q)(this.J,this,a,b));return d}throw new lg(a,b,"Module loaded but service or factory not registered with app contexts.");}return c.gb?(d=new _.df,_.mf(d,c.gb()),d.b(c),_.lf(d,(0,_.q)(this.o,this,a)),d):this.o(a)};_.gg.prototype.o=function(a){this.g[a]&&delete this.g[a];return this.get(a)};_.gg.prototype.G=function(a,b,c){return c instanceof _.ef?c:new mg(a,b,c)};
_.kg=function(a,b,c,d){if(a.H)d||_.x(c);else{a.c[b]=[c,!d];d=ng(a,a,b);for(var e=0;e<d.length;e++)d[e].b(null);delete a.j[b];return c}};ng=function(a,b,c){var d=[],e=a.a[c];e&&(_.Gb(e,function(a){var c;a:{for(c=a.fb;c;){if(c==b){c=!0;break a}c=c.b}c=!1}c&&(d.push(a.d),_.Ob(e,a))}),0==e.length&&delete a.a[c]);return d};og=function(a,b){a.a&&xc(a.a,function(a,d,e){_.Gb(a,function(c){c.fb==b&&_.Ob(a,c)});0==a.length&&delete e[d]})};
_.gg.prototype.D=function(a,b){var c=this.a&&this.a[a];if(c){for(var d=0;d<c.length;++d)if(c[d].fb==this&&c[d].d==b){_.Nb(c,d);break}0==c.length&&delete this.a[a]}};_.gg.prototype.w=function(){if(fg(this)==this){var a=this.h;if(a)for(;a.length;)a[0].$()}else for(var a=fg(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&a[0].$&&a[0].$();this.c=null;this.N&&this.m.$();og(this,this);this.a=null;_.x(this.M);this.I=this.M=null;_.gg.A.w.call(this)};
_.gg.prototype.F=function(){return this.m};var jg=function(a){_.Ca.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.p(jg,_.Ca);var mg=function(a,b,c){_.Ca.call(this);this.message='Module "'+b+'" failed to load when requesting the service "'+a+'" [cause: '+c+"]";this.stack=c.stack+"\nWRAPPED BY:\n"+this.stack};_.p(mg,_.Ca);var lg=function(a,b,c){_.Ca.call(this);this.message='Configuration error when loading the module "'+b+'" for the service "'+a+'": '+c};_.p(lg,_.Ca); pg=new Cb("fva");_.qg=new kc(pg,1);
var rg=function(a){lc.call(this,a);this.O=null;this.b=0};_.p(rg,lc);rg.prototype.Bb=function(a){this.O=a;return this};var sg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];rg.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.tf(6E4);_.y(this,a);var b=new _.Q(this);_.y(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
rg.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<sg.length;++b)if(this.b==sg[b].age){a=sg[b].name;break}if(""!=a){var b=tg.test(_.ub)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.se(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.nb(this.a.a);_.cb(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.ua(this.O)&&this.O(b,a[d].displayName,a[d].value);_.Gf("https://clients2.google.com/cr/staging_perf"+c,ug,"POST","",null,6E4,!0)}}};var ug=function(a){_.Qf(a.target)},tg=/(x86_64|Win64)/;
var wg=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new cf);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=Ha(a)||[]}catch(c){}a=!1;_.xa(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&vg(this)},vg=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Ka(a.a))}catch(b){}};
_.yc.A||_.p(_.yc,ic);_.xg=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
var yg=function(a,b,c,d,e){this.g=_.Rd();this.a=new _.eg((0,_.q)(this.h,this),d);this.a.ca(a,b,e);this.a.a=c;this.b=new _.tf(50);this.b.start();_.Qe(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.j;b=Od(b,b,this);b.g=!0;Yd(a,b)};yg.prototype.j=function(){_.x(this.a);_.Ye(this.b,"tick",this.c,!1,this);_.x(this.b)};yg.prototype.c=function(){this.a.send(1)};yg.prototype.h=function(a,b){2==_.L(a,2)&&this.g.b(b.origin)};
var zg=function(a,b,c){_.u.call(this);this.b=a;a=_.L(b,3);b=_.L(b,1);this.a=new _.eg((0,_.q)(this.g,this),b);this.a.a=a;c&&this.a.ca(c.origin,c.source);_.y(this,this.a)};_.p(zg,_.u);zg.prototype.send=function(a){var b=new wf;_.P(b,4,a);this.a.send(xf.sb,b)};zg.prototype.connect=function(a,b){this.a.ca(a,b);this.a.send(xf.rb)};zg.prototype.g=function(a){_.L(a,2)==xf.sb&&(a=_.N(a,yf,4),this.b(a))};zg.prototype.c=_.ya;
var Bg=function(a,b,c){_.u.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],Ag(this)):(this.a=new _.eg(_.ya,_.L(b,1)),a=_.L(b,3),this.a.a=a)};_.p(Bg,_.u);Bg.prototype.w=function(){Bg.A.w.call(this);this.b&&this.b.close();_.x(this.a)};Bg.prototype.c=function(){this.g=new _.Q(this);_.y(this,this.g);Ag(this)};Bg.prototype.send=function(a){this.b.postMessage(_.O(a))};
Bg.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;Ag(this);var d=this.a;this.a=null;c=c.port2;d.ca(a,b);d.send(xf.ab,void 0,[c]);_.x(d)};var Ag=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};Bg.prototype.j=function(a){a=a.a;var b;try{b=new yf(a.data)}catch(c){return}this.h(b)};
var U=function(a){lc.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.J=!0;this.j=10;this.b=null;this.c=!1};_.p(U,lc);U.prototype.Eb=function(a){this.J=a;return this};U.prototype.setUseLocalStorage=U.prototype.Eb;U.prototype.Cc=function(a){this.j=Math.min(a,100);return this};U.prototype.setMaxErrorsPerHour=U.prototype.Cc;U.prototype.Cb=function(a){this.o=a;return this};U.prototype.setGlobalSampling=U.prototype.Cb;U.prototype.ub=function(a,b){this.m[a]=b;return this};
U.prototype.addPerErrorMessageSampling=U.prototype.ub;U.prototype.Bb=function(a){this.O=a;return this};U.prototype.setCallback=U.prototype.Bb;U.prototype.Bc=function(a){this.g=a;return this};U.prototype.setClientId=U.prototype.Bc;U.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.v.bind(this);this.setEnabled(!0);return!0};U.prototype.enable=U.prototype.enable;
U.prototype.yb=function(a,b,c,d,e){var f=_.se(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ua(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var l=100,n=0;n<h.length;++n){var r=h[n];(new RegExp(r)).test(a)&&(l=this.m[r])}if(h=(100*Math.random()).toFixed(6)>=this.o*l/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new wg(this.j,this.J));if(null===this.b)h=0;else{a:{h=this.b;l=(0,_.ka)();if(h.a.length==h.g)if(h.a[0]<l-36E5)h.a.shift();else{h=!1;break a}h.a.push(l);
vg(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.Sa(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,l="Other",Nc?l="Opera":_.F?l="Internet Explorer":sd?l="Firefox":wd?l="Chrome":xd&&(l="Safari"),h.browser=l,h.browser_version=_.Ae,h.os=_.z("CrOS")?"Chrome OS":_.z("Linux")?"Linux":_.cc()?"Windows":_.z("Android")?"Android":ac()?"iPhone":_.z("iPad")?"iPad":_.z("iPod")?"iPod":_.bc()?"Mac":"Unknown",l=_.ub,n="",_.cc()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(l=n.exec(l))?l[1]:"0.0"):ac()||_.z("iPad")||
_.z("iPod")?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(l=n.exec(l))&&l[1].replace(/_/g,".")):_.bc()?(n=/Mac OS X ([0-9_.]+)/,n=(l=n.exec(l))?l[1].replace(/_/g,"."):"10"):_.z("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(l=n.exec(l))&&l[1]):_.z("CrOS")&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(l=n.exec(l))&&l[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.cb(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,b=
Cg(h),e=null!=e?_.nb(e.stack):"",_.cb(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),Dg(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.nb(this.a.a),_.cb(a)||(f.version=a),Dg(this,"https://clients2.google.com/cr/staging_perf",Cg(f)))};U.prototype.reportError=U.prototype.yb;U.prototype.v=function(a,b,c,d,e){this.yb(a,b,c,d,e);null!=this.l&&_.ua(this.l)&&this.l(a,b,c,d,e)};
var Cg=function(a){var b="",c;for(c in a)b+=_.cb(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},Dg=function(a,b,c,d){d=d||"";var e=_.cb(d)?{}:{"Content-Type":"text/plain"};_.Gf(b+c,a.I.bind(a,b),"POST",d,e,6E4,!0)};U.prototype.I=function(a,b){_.Qf(b.target)};
_.Eg=function(a){var b=_.Be(_.L(a,2));_.I(b,"prop",_.xg(27));_.I(b,"b",1);_.I(b,"hl",_.L(a,3));_.L(a,4)&&_.I(b,"jsmode",_.L(a,4));_.I(b,"zx",_.ob());return b.toString()};var Fg=function(a,b,c){var d=!1;_.m(_.L(b,2))?_.L(b,2)==xf.ab&&(d=!0):d=wd;return d?new Bg(a,b,c):new zg(a,b,c)};var Gg=function(a){_.u.call(this);this.b=new Eb(a);this.a={}};_.p(Gg,_.u);_.qa("webmonitoring.Monitoring",Gg);Gg.prototype.setVersion=function(a){this.b.setVersion(a);return this};Gg.prototype.setVersion=Gg.prototype.setVersion;Gg.prototype.Na=function(a){this.b.Na(a);return this};Gg.prototype.setChannel=Gg.prototype.Na;Gg.prototype.pb=function(a){this.b.pb(a);return this};Gg.prototype.setContext=Gg.prototype.pb;Gg.prototype.Ja=function(){null!=this.a[2]||(this.a[2]=new U(this.b));return this.a[2]}; Gg.prototype.createJsErrorsReporter=Gg.prototype.Ja;
var Kg;_.Hg=function(){_.S.call(this);this.h=null;this.l=!1;this.j=[];this.c=[];_.w(this,this.o,this);this.b=null};_.p(_.Hg,_.S);_.Hg.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.Jg=function(a){a.o();a.j=[];a.b=new _.df;a.c.push((0,_.q)(a.b.cancel,a.b));a.l=!1;_.lf(a.b.h(),function(a){(rc(this.g)||this.J)&&Ig(this);this.c.push(_.sa(_.x,a))},a)};_.g=_.Hg.prototype;_.g.sendMessage=function(a){this.xa(_.O(a))};_.g.xa=function(a){if(this.b){var b=new yf;_.M(b,1,a);_.lf(this.b.h(),function(a){a.send(b)})}};
_.g.qb=function(a){this.h=a;_.w(this,function(){this.h=null},this);Ig(this)};_.g.F=function(){return this};_.g.ca=function(a,b,c){this.a.ca(a,b,c)};_.Lg=function(a,b,c,d){_.Jg(a);Kg(a,b,c,d).then(function(a){var d=new wf;_.M(d,1,a.Ec);_.M(d,3,c);d=Fg((0,_.q)(this.m,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};Kg=function(a,b,c,d){var e=Tf();b=(new yg("*",b,c,e,d)).g.a;a.c.push((0,_.q)(b.cancel,b));return b.then(function(a){return{Ec:e,origin:a}})};
_.Hg.prototype.D=function(a,b){if(_.L(a,2)==xf.rb||_.L(a,2)==xf.ab)_.x(this.a),this.a=null,this.b.b(Fg((0,_.q)(this.m,this),a,b))};_.Hg.prototype.m=function(a){this.j.push(a);this.v()};_.Hg.prototype.v=function(){for(;Mg(this););};var Mg=function(a){if(a.H||!a.l||0==a.j.length)return!1;var b=_.L(a.j.shift(),1);a.h&&a.h.xa(b);_.T(a,new fc(b[0],b));return!0},Ig=function(a){a.l||(a.l=!0,a.b&&_.lf(a.b.h(),function(a){a.c();_.uf(this.v,0,this)},a))}; _.Hg.prototype.listen=function(a,b,c,d){Ig(this);return _.Hg.A.listen.call(this,a,b,c,d)};_.Hg.prototype.La=function(a,b,c,d){Ig(this);return _.Hg.A.La.call(this,a,b,c,d)};_.Hg.prototype.I=function(a){Ig(this);return _.Hg.A.I.call(this,a)};
var Ng=function(a){Gg.call(this,a)};_.p(Ng,Gg);Ng.prototype.Ja=function(){var a=Ng.A.Ja.call(this);a.c=!0;return a};_.Og=function(){var a=new Ng("Google_Hangouts_Chrome");a.Na(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new rg(a.b));a.a[1].enable();a.Ja().Eb(!1).Cb(100).ub("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
try{
var Bp=function(){return[]},Cp=/\s*;\s*/,Dp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.aa[c[0]].prototype[a].apply(this,arguments)}:b[a].Zb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Yb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=
0;e<c.length;++e){var f=this.a[c[e]],f=f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].nc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var r=this.a[c[f]];e.push(r?r[a].apply(r,d):this.aa[c[f]].prototype[a].apply(this,d))}return e}:d||
b[a].Zb||b[a].Yb||b[a].nc?e=null:e=Bp;return e},Ep=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},Fp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.wa(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},Gp=function(a){a=(a.a.cookie||"").split(Cp);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+
1)));return{keys:b,values:c}},Hp=[1],Ip={Ic:_.Vf,Rc:_.Wf,Lc:_.Xf,Mc:_.Yf,Kc:_.Zf,Tc:_.$f},Jp=function(a){_.K(this,a,"ci:ec",null,null)};_.p(Jp,_.J);Jp.messageId="ci:ec";
var Kp=function(a,b){return a.g.get(b)},Lp=function(a){return this.jb.c(a)},Mp=function(a){var b=a.na,c=function(a){c.A.constructor.call(this,a);var b=this.aa.length;this.a=[];for(var d=0;d<b;++d)this.aa[d].Yc||(this.a[d]=new this.aa[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.na){b.aa&&Fp(d,b.aa);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ua(e[f])&&e[f]!==b){var h=!!e[f].Xb,l=Ep(f,e,d,h);(h=Dp(f,e,l,h))&&(c.prototype[f]=h)}}a=a.A&&a.A.constructor}c.prototype.aa=d;return c},Np=function(a){this.a=
a||{cookie:""}};_.g=Np.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("d`"+a);if(/[;\r\n]/.test(b))throw Error("e`"+b);_.m(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.ka)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Cp),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.m(this.get(a));this.set(a,"",0,b,c);return d};_.g.V=function(){return Gp(this).keys};_.g.S=function(){return Gp(this).values};_.g.clear=function(){for(var a=Gp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Op=function(a){_.K(this,a,"capi:r_rstr",null,null)};_.p(Op,_.J);Op.messageId="capi:r_rstr";
var Pp=function(a){_.K(this,a,"capi:r_recl",null,null)};_.p(Pp,_.J);Pp.messageId="capi:r_recl";var Qp=function(a){_.K(this,a,"capi:r_clre",null,null)};_.p(Qp,_.J);Qp.messageId="capi:r_clre";
var Rp=function(a,b,c){if(!this.jb){for(var d=this.constructor;d&&!d.na;)d=d.A&&d.A.constructor;d.na.xb||(d.na.xb=Mp(d));this.jb=new d.na.xb(this);this.c||(this.c=Lp)}var e=this.jb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.ab(e,"https://talkgadget.google.com/talkgadget/")){var d=(new Np(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.Mb(f,d)&&h.test(d)&&(e=_.se(e),
e=_.se("https://"+d+e.a).toString())}this.la=e;this.g=c||new Jp;a.notificationsOnly&&_.M(this.g,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=Kp(new _.H(window.location.href),"authuser"),null!=c&&(this.b=c));this.m=a.clientUrl||"notifierclient";c=Kp(_.se(this.m),"authuser");null!=c&&(this.b=c);this.cb=a.propertyName||"Google Talk";this.J=a.cssUrl;this.locale=a.locale;this.C=a.debug;this.Ha=a.userJid;this.Ea=a.uiVersion;this.gc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.X=a.hostLogMinValue;
this.va=a.hideChat;this.$b=a.refresh;this.M=a.hideProfileCard;this.U=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.N=a.hideRecentConversations;this.K=a.hideOTR;this.eb=a.hostServerMessageCallback||!1;this.Z=a.isCentralRoster;this.ib=a.isFullFrame||!1;this.fc=a.rosterClass||"talk_roster";this.ic=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.ua=a.parentToken;
this.cc=b||!1;this.h=_.m(a.isRtl)?a.isRtl:_.Fa.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Ip)b.push(_.O(Ip[l]))}this.v=a.entityId;this.Fa=a.useQuasarPanels||!1;this.wa=a.silent||!1;this.hb=a.ignoreCentralRoster||!1;this.bc=a.lazy||!1;this.Qa=a.handleProfileLinks||!1;this.Y=a.hostSettings;this.l=a.screen;this.I=a.docsConfig;this.ac=a.jsmode;this.ta=a.moleWidth;this.ga=a.moleHeight;this.fa=a.minimizedMoleHeight||36;this.jc=a.derp;this.Da=window.location.protocol+
"//"+window.location.host;this.j="";this.G=a.optOutAllowed;this.D=a.legacyTalkSignedIn;this.Ga=a.useSpareMole;this.o=a.conversationId};Rp.na=_.yc;var Sp=function(a){_.K(this,a,0,Hp,null)};_.p(Sp,_.J);var Tp=function(a){_.K(this,a,"uv_r_hrd",null,null)};_.p(Tp,_.J);Tp.messageId="uv_r_hrd";var Up=function(a){_.K(this,a,"uv_r_rrr",null,null)};_.p(Up,_.J);Up.messageId="uv_r_rrr";var Vp=function(a){_.K(this,a,"uv_r_rdr",null,null)};_.p(Vp,_.J);Vp.messageId="uv_r_rdr";
var Wp=function(a){_.K(this,a,0,null,null)};_.p(Wp,_.J);var Xp=function(a){_.K(this,a,0,null,null)};_.p(Xp,_.J);var Yp=function(a){_.K(this,a,0,null,null)};_.p(Yp,_.J);var Zp=function(a){_.K(this,a,0,null,null)};_.p(Zp,_.J);var $p=function(a){_.K(this,a,"h_cc",null,null)};_.p($p,_.J);$p.messageId="h_cc";
var aq=function(a,b){_.Sd(a,null,b,void 0)},bq=function(a,b,c){_.Zd(a,b,c,null)||_.jd(_.sa(b,a))},cq=function(a){return new _.Ld(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],bq(n,_.sa(f,l),h);else b(e)})};
var dq=function(a){_.D.call(this,a[0]);this.P=a};_.p(dq,_.D);var eq=new _.B("q"),fq=new _.B("r");var gq=function(a){var b=_.te(_.L(a,2),"/webchat/extension-start");_.L(a,5)&&_.I(b,"e",_.L(a,5));return new _.Ld(function(a,d){_.Gf(b,function(b){_.Qf(b.target)||d();try{var c=JSON.parse(_.Rf(b.target));a(new _.Af(c))}catch(h){d(h.message)}})})};var hq=function(a){_.S.call(this);this.a=a.get(fq);a=new _.Q(this);_.y(this,a);a.listen(this.a.F(),"uv_r_frm",this.b);a.listen(this.a.F(),"uv_r_rdm",this.c)};_.p(hq,_.S);hq.prototype.reload=function(a){var b=new _.bg;_.M(b,1,a);this.a.sendMessage(b)};hq.prototype.b=function(a){a=new _.cg(a.P);_.T(this,new iq(!!_.L(a,1)))};hq.prototype.c=function(a){a=new _.ag(a.P);_.T(this,new jq(_.L(a,1)))};var iq=function(a){_.D.call(this,"uv_r_frm");this.a=a};_.p(iq,_.D); var jq=function(a){_.D.call(this,"uv_r_rdm");this.a=a};_.p(jq,_.D);
var kq=function(a){this.a=a;_.F||(delete this.a.lpu,delete this.a.ppu)},lq=["cn","tp"],mq=function(a,b){var c;if(_.ua(window.document.postMessage)||_.ua(window.postMessage)||_.F&&window.postMessage)c=1;else if(_.Pc)c=2;else{var d;if(d=_.F){d=!1;try{c=window.opener,window.opener={},d=_.Ya(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new kq(d)};_.qa("GTalk_IFrameChannelConfig.build",mq);
var nq=function(a,b,c,d,e){_.u.call(this);this.a=a;this.b=d||window.document;this.g=new _.Q(this);_.y(this,this.g);var f=_.ub;d=new _.H(a.la+a.m);_.Fe(a.g,2,!1)||(_.I(d,"ts","0"),_.I(d,"re",a.gc),_.I(d,"ref",a.$b));_.I(d,"client","sm");_.I(d,"prop",a.cb);_.I(d,"nav","true");_.I(d,"fid",a.a);a.C&&_.I(d,"debug",a.C);_.I(d,"os",_.Sc);_.I(d,"stime",c);a.va&&_.I(d,"hc",a.va);for(c=0;c<lq.length;++c);b=_.Ka(b.a);_.I(d,"xpc",b);_.I(d,"ec",_.Ka(_.O(a.g)));a.l&&_.I(d,"screen",a.l);-1!=f.indexOf("MSIE")&&_.I(d,
"ua",f);a.ua&&_.I(d,"pvt",a.ua);a.eb&&_.I(d,"hsmc","true");_.m(a.X)&&_.I(d,"logl",a.X);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.I(d,"href",b.join("?")));b=new _.H(window.location.href);"false"==Kp(b,"uacheck")&&_.I(d,"uacheck",!1);(f=a.ac)&&_.I(d,"jsmode",f);(f=Kp(b,"cssmode"))&&_.I(d,"cssmode",f);(f=Kp(b,"convid"))&&_.I(d,"convid",f);if(f=b.g.S("convp"))_.xa(f)||(f=[String(f)]),_.ye(d.g,"convp",f);(f=Kp(b,"smexp"))&&_.I(d,"smexp",
f);f=b.g.S("mods");a.bc&&f.push("lazy");e&&(f=_.Pb(f,e));0<f.length&&_.I(d,"mods",f.join(","));if(!a.la||0>a.la.indexOf("/u/"))(e=Kp(b,"authuser"))?_.I(d,"authuser",e):null!=a.b&&_.I(d,"authuser",a.b);e=Kp(b,"eid");_.cb(_.nb(e))||_.I(d,"eid",e);_.cb(_.nb(this.a.v))||_.I(d,"eid",this.a.v);null!=this.a.position&&_.I(d,"pos",this.a.position);_.m(a.Ea)&&_.I(d,"uiv",this.a.Ea);a.J&&_.I(d,"css",a.J);e=a.locale||Kp(b,"hl");null!=e&&_.I(d,"hl",e);_.m(a.Ha)&&_.I(d,"uj",a.Ha);null!=a.M&&_.I(d,"hpc",a.M);null!=
a.U&&_.I(d,"hsm",a.U);null!=a.T&&_.I(d,"hro",a.T);null!=a.N&&_.I(d,"hrc",a.N);null!=a.K&&_.I(d,"hotr",a.K);null!=a.Z&&_.I(d,"pop",a.Z);a.cc&&_.I(d,"pal","1");null!=a.Fa&&_.I(d,"uqp",a.Fa);null!=a.G&&_.I(d,"gooa",a.G);null!=a.D&&_.I(d,"gltsi",a.D);null!=a.Ga&&_.I(d,"gusm",a.Ga);null!=a.wa&&_.I(d,"sl",a.wa);a.hb&&_.I(d,"icr","1");a.Qa&&_.I(d,"hpl","1");a.Y&&_.I(d,"hs",a.Y);a.I&&_.I(d,"dc",_.Ka(_.O(a.I)));null!=a.ta&&_.I(d,"molew",a.ta);null!=a.ga&&_.I(d,"moleh",a.ga);null!=a.fa&&_.I(d,"mmoleh",a.fa);
a.jc&&_.I(d,"derp","1");a.j&&_.I(d,"fcho",a.j);null!=a.Da&&_.I(d,"two",a.Da);null!=a.o&&_.I(d,"convid",a.o);_.I(d,"host","1");_.I(d,"zx",_.ob());this.c=d.toString()};_.p(nq,_.u);
var oq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.fc,a.b.body.appendChild(e));a=(0,_.q)(function(){var a="";this.a.ib||(a="height:400px");var b=this.b.createElement("iframe");_.Fd(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.Dd("talk_loading_msg",e)||_.Id(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.sf(this.g,l,["load","error"],function(a){l.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});l.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var pq=function(a){_.S.call(this);this.a=a.get(_.E);a=new _.Q(this);_.y(a,a);a.listen(this.a.F(),"capi:r_clre",this.h);a.listen(this.a.F(),"capi:r_rrst",this.b);a.listen(this.a.F(),"capi:r_rers",this.c)};_.p(pq,_.S);pq.prototype.h=function(a){a=new Qp(a.P);_.T(this,new qq(_.N(a,Sp,1)))};pq.prototype.c=function(){_.T(this,"I")};pq.prototype.b=function(){_.T(this,"H")};var qq=function(a){_.D.call(this,"G");this.a=a};_.p(qq,_.D);
var rq=function(a){var b=_.k.GTalkNotifier;return b?_.Pd(b):new _.Ld(function(c,d){var e=_.uf(function(){return d("chat.host.Client is not available!")},25E3),f=window.document.createElement("SCRIPT");f.src=_.Eg(a);f.addEventListener("load",function(){_.vf(e);(b=_.k.GTalkNotifier)?c(b):d("chat.host.Client is not available!")});f.addEventListener("error",function(){_.vf(e);d("chat.host.Client is not available!")});window.document.body.appendChild(f)})};
var sq=function(a){_.Q.call(this);this.b=a.get(_.hc);this.a=a.get(eq);this.listen(this.a,"uv_r_rdm",this.Vb);this.listen(this.a,"uv_r_frm",this.Ub);this.listen(this.b,"G",this.wc);this.listen(this.b,"H",this.Tb);this.listen(this.b,"I",this.Wb)};_.p(sq,_.Q);_.g=sq.prototype;_.g.wc=function(a){a=(a=a.a)?[_.O(a)]:[void 0];this.a.reload(a)};_.g.Tb=function(){var a=this.a,b=new Vp;a.a.sendMessage(b)};_.g.Ub=function(a){var b=this.b;a=!!a.a;var c=new Pp;_.M(c,1,!!a);b.a.sendMessage(c)}; _.g.Vb=function(a){if(a.a&&(a=a.a[0])){a=new Sp(a);var b=this.b,c=new Op;_.P(c,1,a);b.a.sendMessage(c)}};_.g.Wb=function(){var a=this.a,b=new Up;a.a.sendMessage(b)};
var uq=function(a,b){_.u.call(this);this.m=(0,_.ka)();var c={},d=_.Fe(a,1,"hangouts.google.com"),e="";0>d.indexOf("://")&&(e="https://",0<=d.indexOf(":")&&23!=_.L(a,2)&&27!=_.L(a,2)&&(e="http://"));-1!=d.indexOf("talkgadget.")?(c.clientBaseUrl=e+d+"/talkgadget/_/",c.clientUrl="chat"):(c.clientBaseUrl=e+d+"/webchat/u/"+_.Fe(a,8,"0")+"/",c.clientUrl="load");c.authUser=_.Fe(a,8,"0");c.propertyName=_.xg(_.L(a,2));c.locale=_.L(a,4);c.hideProfileCard=!0;c.parentToken=_.L(a,3);c.isRtl=_.Fe(a,6,!1);c.lazy=
_.Fe(a,7,!1);c.entityId=_.L(a,9);c.hostSettings=_.L(a,5);c.jsmode=_.L(a,11);c.isFullFrame=_.Fe(a,13,!1);c.rosterId=_.Fe(a,12,"talk_roster");c.rosterIframeIdB=_.Fe(a,15,"gtn-roster-iframe-id-b");c.derp=!!_.Fe(a,16,!1);d=_.N(a,Wp,14);null!=d&&(c.isCentralRoster=_.Fe(d,1,!1),c.useQuasarPanels=_.Fe(d,2,!1));d=_.N(a,Zp,10);null!=d&&(c.moleManagerLeftMargin=_.L(d,1),c.moleManagerMiddleMargin=_.L(d,2),c.moleManagerRightMargin=_.L(d,3),c.moleManagerNoMoleAreaMargin=_.L(d,4),c.moleManagerBoundingElementId=
_.L(d,5),c.moleWidth=_.L(d,6),c.moleHeight=_.L(d,7),c.minimizedMoleHeight=_.L(d,8));d=_.N(a,Yp,18);null!=d&&(c.optOutAllowed=_.Fe(d,1,!0),e=_.N(d,Xp,3),null!=e&&(c.legacyTalkSignedIn=_.Fe(e,1,!0)),d=_.L(d,4),null!=d&&(c.useSpareMole=d));c.uiVersion=2;c.hideStatusMsgs=!0;c.hideRecentConversations=!0;d=new Jp;_.M(d,2,!0);_.M(d,1,!0);_.M(d,3,!1);c.endpointConfig=d;c.ignoreAutomatedRoster=_.Fe(a,17,!1);c.conversationId=_.L(a,19);this.c=c;a=this.a=new Rp(this.c,!0,this.c.endpointConfig);var f=this.a.la,
c=this.a.b;if(-1!=f.indexOf("talkgadget."))if(d=_.se(f),e=d.a,0<=e.indexOf("/u/"))c=f;else{f=e.lastIndexOf("_/");if(0>f||f!=e.length-2)e+="_/";d.a="/u/"+c+e;c=d.toString()}else c=f;a.la=c;this.a.j=window.location.origin;this.b=null;this.l=new _.S;a=_.Sa(this.c);a.endpointConfig=_.O(this.a.g);this.h=new b(a,!0);this.j=new _.Hg;_.y(this,this.j);tq(this)};_.p(uq,_.u);uq.prototype.sendMessage=function(a){this.xa(_.O(a))};uq.prototype.xa=function(a){this.g("_h",a)};
uq.prototype.qb=function(a){this.b=a;_.w(this,function(){this.b=null},this)};uq.prototype.F=function(){return this.l};var tq=function(a){var b=mq(a.a.la,a.a.a),b=new nq(a.a,b,a.m,window.document);_.y(a,b);oq(b,a.a.ic,function(){},function(){return vq(a)})},vq=function(a){_.Lg(a.j,window.document.getElementById(a.a.a).contentWindow,"31ACFC0_","google.com");a.g("_addClientMessageCallback",function(b){a.b&&a.b.xa(b);_.T(a.l,new dq(b))});a.g("_rosterIframeLoaded")}; uq.prototype.g=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.h[a]&&this.h[a].apply(this.h,c)};
var xq=function(){_.Q.call(this);_.A("Starting ...");this.a=new _.gg;_.y(this,this.a);this.h=null;this.c=[];this.listen(window,"unload",this.$);this.b=new _.dg(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));var a=_.L(this.b,1),b=new _.Hg;_.Jg(b);b.a=new _.eg((0,_.q)(b.D,b),a);b.a.ca("*",void 0,void 0);b.c.push(_.sa(_.x,b.a));this.g=b;_.kg(this.a,fq,this.g);wq(this)},yq;_.p(xq,_.Q);
var wq=function(a){_.A("Initializing ...");aq(cq([gq(a.b).then(a.j,void 0,a),rq(a.b)]).then(function(b){_.ga();var c=b[window.Symbol.iterator];b=c?c.call(b):_.fa(b);var d=b.next().value;b=b.next().value;if(a.H)b=null;else{var c=new $p,e=_.se(_.L(a.b,2)),f=e.b;null!=e.c&&(f+=":"+e.c);_.M(c,1,f);_.M(c,2,27);_.M(c,13,!0);_.M(c,17,!0);d=_.L(d,1);_.M(c,3,d);d=_.L(a.b,4);_.M(c,11,d);d=_.L(a.b,3)||"en";_.M(c,4,d);d=new Wp;_.M(d,2,!0);_.M(d,1,!0);_.P(c,14,d);b=new uq(c,b)}return b}).then(function(b){if(!a.H){b.qb(a.g);
a.g.qb(b);a.h=b;_.kg(a.a,_.E,a.h);b=new hq(a.a);_.kg(a.a,eq,b);_.kg(a.a,_.hc,new pq(a.a));new sq(a.a);for(a.g.sendMessage(new Tp);a.c.length;)a.c.shift()();a.c=null}}),function(a){_.A("Failed to start : %s.",a||"")})};xq.prototype.j=function(a){var b=this;return new _.Ld(function(c,d){b.g.sendMessage(a);_.L(a,1)||d("Unauthenticated");c(a)})};_.qa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Og();if(!_.m(yq)||null==yq||yq.H)yq=new xq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
